#!/bin/bash
# Copyright 2018 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd "$(dirname "$0")/../.."

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

# HTTP settings, for driving nginx.
export MAAS_HTTP_CONFIG_DIR="${MAAS_DATA}/http"

# Ensure that we've got a configuration directory.
mkdir -p "${MAAS_HTTP_CONFIG_DIR}"

# Create HTTP config.
homedir="$MAAS_HTTP_CONFIG_DIR"
bin/py -m provisioningserver.testing.nginxfixture -- \
    --create-config-only --overwrite-config \
    --homedir "${homedir}"

# Run nginx.
exec $(command -v bin/py) \
    -m provisioningserver.testing.nginxfixture -- \
    --homedir "${homedir}"
