#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit

# Move to the project root.
cd "$(dirname "$0")/../.."

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

homedir=`pwd`/run/named
port=5246
rndc_port=5247
# Create DNS config.
bin/py -m maastesting.bindfixture -- \
    --create-config-only --overwrite-config \
    --homedir $homedir \
    --port $port --rndc-port $rndc_port
# Create MAAS' DNS config: do not overwrite an existing config file
# as the writing of the full configuration might have happened already.
./bin/maas set_up_dns --no-clobber
# Edit the fixture's named.conf to include MAAS' DNS config.
./bin/maas get_named_conf --edit --config_path \
    `pwd`/run/named/named.conf
# Run named.
exec bin/py -m maastesting.bindfixture -- \
    --homedir $homedir \
    --port $port --rndc-port $rndc_port
