# Generated by Django 1.11.1 on 2017-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0122_make_virtualblockdevice_uuid_editable")
    ]

    operations = [
        migrations.AlterField(
            model_name="iprange",
            name="comment",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True
            ),
        )
    ]
