# Generated by Django 1.11.6 on 2018-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0138_add_ip_and_user_agent_to_event_model")
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="endpoint",
            field=models.IntegerField(
                choices=[(0, "API"), (1, "WebUI")], default=0, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="user_agent",
            field=models.TextField(blank=True, default="", editable=False),
        ),
    ]
