# Generated by Django 1.11.9 on 2018-02-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0142_pod_default_resource_pool")]

    operations = [
        migrations.AddField(
            model_name="physicalblockdevice",
            name="firmware_version",
            field=models.CharField(
                blank=True,
                default="Unknown",
                help_text="Firmware version of block device.",
                max_length=255,
            ),
        )
    ]
