# Generated by Django 1.11.9 on 2018-02-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0143_blockdevice_firmware")]

    operations = [
        migrations.AlterField(
            model_name="filesystem",
            name="fstype",
            field=models.CharField(
                choices=[
                    ("ext2", "ext2"),
                    ("ext4", "ext4"),
                    ("xfs", "xfs"),
                    ("fat32", "fat32"),
                    ("vfat", "vfat"),
                    ("lvm-pv", "lvm"),
                    ("raid", "raid"),
                    ("raid-spare", "raid-spare"),
                    ("bcache-cache", "bcache-cache"),
                    ("bcache-backing", "bcache-backing"),
                    ("swap", "swap"),
                    ("ramfs", "ramfs"),
                    ("tmpfs", "tmpfs"),
                    ("btrfs", "btrfs"),
                    ("zfsroot", "zfsroot"),
                ],
                default="ext4",
                max_length=20,
            ),
        )
    ]
