# Generated by Django 1.11.9 on 2018-02-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0144_filesystem_zfsroot_support")]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="firmware_version",
            field=models.CharField(
                blank=True,
                help_text="Firmware version of the interface.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="product",
            field=models.CharField(
                blank=True,
                help_text="Product name of the interface.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="vendor",
            field=models.CharField(
                blank=True,
                help_text="Vendor name of interface.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicalblockdevice",
            name="firmware_version",
            field=models.CharField(
                blank=True,
                help_text="Firmware version of block device.",
                max_length=255,
                null=True,
            ),
        ),
    ]
