# Generated by Django 1.11.6 on 2018-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0145_interface_firmware")]

    operations = [
        migrations.CreateModel(
            name="RootKey",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("material", models.BinaryField()),
                ("expiration", models.DateTimeField()),
            ],
            options={"abstract": False},
            bases=[models.Model],
        )
    ]
