# Generated by Django 1.11.9 on 2018-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0148_add_tags_on_pods")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_last_check",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
