# Generated by Django 1.11.9 on 2018-03-16 04:43

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0149_userprofile_auth_last_check")]

    operations = [
        migrations.AddField(
            model_name="bmc",
            name="cpu_over_commit_ratio",
            field=models.FloatField(
                default=1, validators=[MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="bmc",
            name="memory_over_commit_ratio",
            field=models.FloatField(
                default=1, validators=[MinValueValidator(0)]
            ),
        ),
    ]
