# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("maasserver", "0151_userprofile_is_local")]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="local",
            field=models.BooleanField(default=True),
        )
    ]
