# Generated by Django 1.11.11 on 2018-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0152_add_usergroup_local")]

    operations = [
        migrations.AddField(
            model_name="node",
            name="skip_bmc_config",
            field=models.BooleanField(default=False),
        )
    ]
