# Generated by Django 1.11.11 on 2018-04-04 09:38

from django.db import migrations, models


def forwards(apps, schema_editor):
    Role = apps.get_model("maasserver", "Role")
    UserGroup = apps.get_model("maasserver", "UserGroup")
    default_pool_role = Role.objects.get(resource_pools__id=0)
    default_usergroup = UserGroup.objects.get(id=0)
    # link users to the pool via the default group, not directly
    default_pool_role.users.clear()
    default_pool_role.groups.add(default_usergroup)


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0153_add_skip_bmc_config")]

    operations = [
        migrations.AddField(
            model_name="role",
            name="groups",
            field=models.ManyToManyField(to="maasserver.UserGroup"),
        ),
        migrations.RunPython(forwards),
    ]
