# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("maasserver", "0155_add_globaldefaults_model")]

    operations = [
        migrations.AlterUniqueTogether(name="sshkey", unique_together=set([]))
    ]
