# Generated by Django 1.11.11 on 2018-05-14 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0156_drop_ssh_unique_key_index")]

    operations = [
        migrations.RemoveField(model_name="role", name="groups"),
        migrations.RemoveField(model_name="role", name="resource_pools"),
        migrations.RemoveField(model_name="role", name="users"),
        migrations.RemoveField(model_name="usergroup", name="users"),
        migrations.RemoveField(model_name="usergroupmembership", name="group"),
        migrations.RemoveField(model_name="usergroupmembership", name="user"),
        migrations.DeleteModel(name="Role"),
        migrations.DeleteModel(name="UserGroup"),
        migrations.DeleteModel(name="UserGroupMembership"),
    ]
