# Generated by Django 1.11.11 on 2018-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0158_pod_default_pool_to_pod")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="auth_last_check",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
