# Generated by Django 1.11.11 on 2018-05-04 09:43

from django.db import migrations, models
import django.db.models.deletion

import maasserver.models.cleansave


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0160_pool_only_for_machines")]

    operations = [
        migrations.CreateModel(
            name="PodStoragePool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pool_id", models.CharField(max_length=255)),
                ("pool_type", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=4095)),
                ("storage", models.BigIntegerField(default=0)),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_pools",
                        to="maasserver.BMC",
                    ),
                ),
            ],
            bases=(maasserver.models.cleansave.CleanSave, models.Model),
        ),
        migrations.AddField(
            model_name="bmc",
            name="default_storage_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maasserver.PodStoragePool",
            ),
        ),
        migrations.AddField(
            model_name="physicalblockdevice",
            name="storage_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Storage pool that this block device belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="block_devices",
                to="maasserver.PodStoragePool",
            ),
        ),
    ]
