# Generated by Django 1.11.11 on 2018-06-02 03:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0162_storage_pools_notification")]

    operations = [
        migrations.AddField(
            model_name="bmc",
            name="new_power_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default="", max_length=32768
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="new_instance_power_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default="", max_length=32768
            ),
        ),
    ]
