# Generated by Django 1.11.11 on 2018-06-26 14:16

from django.db import migrations


def add_s390x_to_pkg_repository_to_arches(apps, schema_editor):
    arches = ["armhf", "arm64", "ppc64el", "s390x"]
    PackageRepository = apps.get_model("maasserver", "PackageRepository")
    repo = PackageRepository.objects.get(
        url="http://ports.ubuntu.com/ubuntu-ports"
    )
    repo.arches = arches
    repo.save()


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0165_remove_and_rename_power_parameters")]

    operations = [migrations.RunPython(add_s390x_to_pkg_repository_to_arches)]
