# Generated by Django 1.11.11 on 2018-07-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0166_auto_select_s390x_extra_arches")]

    operations = [
        migrations.AddField(
            model_name="bmc",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosted_pods",
                to="maasserver.Node",
            ),
        )
    ]
