# Generated by Django 1.11.11 on 2018-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0167_add_pod_host")]

    operations = [
        migrations.AddField(
            model_name="bmc",
            name="default_macvlan_mode",
            field=models.CharField(
                max_length=32,
                null=True,
                blank=True,
                default=None,
                choices=[
                    ("bridge", "bridge"),
                    ("passthru", "passthru"),
                    ("private", "private"),
                    ("vepa", "vepa"),
                ],
            ),
        )
    ]
