# Generated by Django 1.11.11 on 2018-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0168_add_pod_default_macvlan_mode")]

    operations = []
