# Generated by Django 1.11.11 on 2018-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0173_add_node_install_kvm")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="node_system_id",
            field=models.CharField(
                blank=True, editable=False, max_length=41, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user_id_migrate",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
