# Generated by Django 1.11.11 on 2018-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0179_rbacsync")]

    operations = [
        migrations.CreateModel(
            name="RBACLastSync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        editable=False,
                        help_text="Resource type that as been sync'd.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "sync_id",
                    models.CharField(
                        editable=False,
                        help_text="ID returned by the RBAC service after the last sync.",
                        max_length=255,
                    ),
                ),
            ],
        )
    ]
