# Generated by Django 1.11.11 on 2019-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0185_vmfs6")]

    operations = [
        migrations.AddField(
            model_name="node",
            name="description",
            field=models.TextField(blank=True, default=""),
        )
    ]
