# Generated by Django 1.11.11 on 2019-06-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0187_status_messages_change_event_logging_levels")
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="interface_speed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interface",
            name="link_connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="interface",
            name="link_speed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
