# Generated by Django 1.11.11 on 2019-08-08 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0190_bmc_clean_duplicates")]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX maasserver_bmc_power_type_parameters_idx"
            " ON maasserver_bmc (power_type, power_parameters)"
            " WHERE (power_type != 'manual')"
        )
    ]
