# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-23 07:27
from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maasserver', '0191_bmc_unique_power_type_and_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='node',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maasserver.Node'),
        ),
    ]
