# Generated by Django 1.11.11 on 2019-08-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        # depend on the latest patch in the 2.6 branch as this is meant to be
        # backported there.
        ("maasserver", "0187_status_messages_change_event_logging_levels")
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="node",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="maasserver.Node",
            ),
        )
    ]
