# Generated by Django 1.11.11 on 2019-09-02 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0192_event_node_no_set_null"),
        ("maasserver", "0191_bmc_unique_power_type_and_parameters"),
    ]

    operations = []
