# Generated by Django 1.11.11 on 2019-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    # This depends on the latest (at time of writing) patch in 2.6,
    # since this patch is to be backported there.
    dependencies = [("maasserver", "0192_event_node_no_set_null")]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["node", "-created", "-id"],
                name="maasserver__node_id_e4a8dd_idx",
            ),
        )
    ]
