# Generated by Django 1.11.11 on 2019-09-02 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0193_merge_maasserver_0191_1092"),
        ("maasserver", "0194_machine_listing_event_index"),
    ]

    operations = []
