# Generated by Django 1.11.11 on 2019-08-08 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0197_remove_duplicate_physical_interfaces")
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX maasserver_interface_type_mac_address_idx"
            " ON maasserver_interface (type, mac_address)"
            " WHERE (type = 'physical')"
        )
    ]
