# Generated by Django 1.11.11 on 2019-10-08 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0200_interface_sriov_max_vf"),
        ("maasserver", "0195_event_username_max_length"),
    ]

    operations = []
