# Generated by Django 1.11.11 on 2020-03-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0204_interface_node_name_unique_together")]

    operations = [
        migrations.AddField(
            model_name="podhints",
            name="nodes",
            field=models.ManyToManyField(to="maasserver.Node"),
        )
    ]
