# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-19 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("maasserver", "0204_interface_node_name_unique_together")]

    operations = [
        migrations.AddField(
            model_name="podhints",
            name="nodes",
            field=models.ManyToManyField(
                related_name="pods",
                related_query_name="pods",
                to="maasserver.Node",
            ),
        )
    ]
