# Generated by Django 1.11.11 on 2020-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0208_no_power_query_events")]

    operations = [
        migrations.AlterField(
            model_name="partitiontable",
            name="table_type",
            field=models.CharField(
                choices=[
                    ("MBR", "Master boot record"),
                    ("GPT", "GUID parition table"),
                ],
                default="GPT",
                max_length=20,
            ),
        )
    ]
