# Generated by Django 1.11.11 on 2020-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0209_default_partitiontable_gpt")]

    operations = [
        migrations.AlterField(
            model_name="blockdevice",
            name="id_path",
            field=models.CharField(
                blank=True,
                help_text="Path of by-id alias. (e.g. /dev/disk/by-id/wwn-0x50004...)",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bootsource",
            name="keyring_filename",
            field=models.CharField(
                blank=True,
                help_text="The path to the keyring file for this BootSource.",
                max_length=4096,
            ),
        ),
    ]
