# Generated by Django 1.11.11 on 2020-06-29 09:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("maasserver", "0210_filepathfield_to_charfield")]

    operations = [
        migrations.AlterField(
            model_name="bmc",
            name="power_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=str, max_length=32768
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="instance_power_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=str, max_length=32768
            ),
        ),
    ]
