# Generated by Django 2.2.12 on 2020-08-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0213_virtual_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualmachine",
            name="machine",
            field=models.OneToOneField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="virtualmachine",
                to="maasserver.Machine",
            ),
        ),
    ]
