# Generated by Django 2.2.12 on 2020-09-04 12:33

from django.db import migrations, models
import django.db.models.deletion

import maasserver.models.cleansave


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0214_virtualmachine_one_to_one"),
    ]

    operations = [
        migrations.CreateModel(
            name="NUMANodeHugepages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("page_size", models.BigIntegerField()),
                ("total", models.BigIntegerField()),
                (
                    "numanode",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hugepages_set",
                        to="maasserver.NUMANode",
                    ),
                ),
            ],
            options={
                "unique_together": {("numanode", "page_size")},
            },
            bases=(
                maasserver.models.cleansave.CleanSave,
                models.Model,
                object,
            ),
        ),
    ]
