# Generated by Django 2.2.12 on 2020-09-04 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0215_numanode_hugepages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="skip_bmc_config",
        ),
    ]
