# Generated by Django 2.2.12 on 2021-01-22 16:45

from django.db import migrations, models

CREATION_TYPE_DYNAMIC = 3


def fill_node_dynamic(apps, schema_editor):
    Node = apps.get_model("maasserver", "Node")
    Node.objects.filter(creation_type=CREATION_TYPE_DYNAMIC).update(
        dynamic=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0221_track_lxd_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="dynamic",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fill_node_dynamic),
        migrations.RemoveField(
            model_name="node",
            name="creation_type",
        ),
    ]
