# Generated by Django 2.2.12 on 2021-02-22 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0225_drop_rsd_pod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bmc",
            name="iscsi_storage",
        ),
        migrations.RemoveField(
            model_name="podhints",
            name="iscsi_storage",
        ),
    ]
