# Generated by Django 2.2.12 on 2021-02-23 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0226_drop_iscsi_storage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bmc",
            name="local_disks",
        ),
        migrations.RemoveField(
            model_name="podhints",
            name="local_disks",
        ),
    ]
