# Generated by Django 2.2.12 on 2021-02-23 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0227_drop_pod_local_storage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ISCSIBlockDevice",
        ),
    ]
