# Generated by Django 2.2.12 on 2021-02-17 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0228_drop_iscsiblockdevice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physicalblockdevice",
            name="storage_pool",
        ),
    ]
