# Generated by Django 2.2.12 on 2021-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0230_tag_kernel_opts_blank_instead_of_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmc",
            name="version",
            field=models.TextField(blank=True, default=""),
        ),
    ]
