# Generated by Django 2.2.12 on 2021-03-18 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0231_bmc_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controllerinfo",
            name="interface_update_hints",
        ),
        migrations.RemoveField(
            model_name="controllerinfo",
            name="interfaces",
        ),
    ]
