# Generated by Django 2.2.12 on 2021-03-24 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0232_drop_controllerinfo_interface_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Switch",
        ),
    ]
