# Generated by Django 2.2.12 on 2021-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0234_node_register_vmhost"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllerinfo",
            name="install_type",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("snap", "snap"), ("deb", "deb")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="controllerinfo",
            name="snap_cohort",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="controllerinfo",
            name="snap_revision",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="controllerinfo",
            name="snap_update_revision",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="controllerinfo",
            name="update_origin",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="controllerinfo",
            name="update_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="controllerinfo",
            name="version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
