# Generated by Django 2.2.12 on 2021-04-20 14:25

from django.db import migrations


def drop_notifications(apps, schema_editor):
    Notification = apps.get_model("maasserver", "Notification")
    Notification.objects.filter(
        ident__startswith="controller_out_of_date_"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0236_controllerinfo_update_first_reported"),
    ]

    operations = [
        migrations.RunPython(drop_notifications),
    ]
