# Generated by Django 2.2.12 on 2021-04-30 00:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0237_drop_controller_version_mismatch_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnet",
            name="disabled_boot_architectures",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
