# Generated by Django 2.2.12 on 2021-09-15 15:45

from django.db import migrations, models
import django.db.models.deletion

import maasserver.models.cleansave


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0246_bootresource_custom_base_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VMCluster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("name", models.TextField(unique=True)),
                ("project", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=(maasserver.models.cleansave.CleanSave, models.Model),
        ),
        migrations.AddField(
            model_name="podhints",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maasserver.VMCluster",
            ),
        ),
    ]
