# Generated by Django 2.2.12 on 2021-10-06 18:29
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion

from maasserver.models import Zone
import maasserver.models.node


def get_default_zone():
    default_zone_name = "default"
    now = datetime.now()

    zone, _ = Zone.objects.get_or_create(
        name=default_zone_name,
        defaults={
            "name": default_zone_name,
            "created": now,
            "updated": now,
        },
    )
    return zone.id


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0247_auto_20210915_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmcluster",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maasserver.ResourcePool",
            ),
        ),
        migrations.AddField(
            model_name="vmcluster",
            name="zone",
            field=models.ForeignKey(
                default=get_default_zone,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="maasserver.Zone",
                verbose_name="Physical zone",
            ),
        ),
    ]
