# Generated by Django 2.2.12 on 2021-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0249_lxd_auth_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="last_applied_storage_layout",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
