# Generated by Django 2.2.12 on 2021-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0250_node_last_applied_storage_layout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmc",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="bmc",
            constraint=models.UniqueConstraint(
                condition=models.Q(power_parameters__project__exists=False),
                fields=("name",),
                name="name-unique",
            ),
        ),
    ]
