# Generated by Django 2.2.12 on 2021-11-19 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0251_auto_20211027_2128"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FanNetwork",
        ),
    ]
