# Generated by Django 2.2.12 on 2022-01-07 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0255_node_current_config"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE maasserver_blockdevice
            SET node_config_id = maasserver_node.current_config_id
            FROM maasserver_node
            WHERE maasserver_blockdevice.node_id = maasserver_node.id
            """
        ),
    ]
