# Generated by Django 2.2.12 on 2022-01-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0255_node_current_config"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE maasserver_blockdevice
            SET node_config_id = maasserver_node.current_config_id
            FROM maasserver_node
            WHERE maasserver_blockdevice.node_id = maasserver_node.id
            """
        ),
        migrations.AlterField(
            model_name="blockdevice",
            name="node_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="maasserver.NodeConfig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockdevice",
            unique_together={("node_config", "name")},
        ),
        migrations.RemoveField(
            model_name="blockdevice",
            name="node",
        ),
    ]
