# Generated by Django 2.2.12 on 2022-01-27 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0256_blockdevice_nodeconfig_only"),
    ]

    operations = [
        migrations.RunSQL(
            """
            WITH fs_nodeconfig AS (
              SELECT
                fs.id AS id,
                COALESCE(
                  node.current_config_id,
                  bdev.node_config_id,
                  ptable_bdev.node_config_id
                ) AS node_config_id
              FROM maasserver_filesystem AS fs
              LEFT JOIN maasserver_node AS node
                ON fs.node_id = node.id
              LEFT JOIN maasserver_blockdevice AS bdev
                ON fs.block_device_id = bdev.id
              LEFT JOIN maasserver_partition AS part
                ON fs.partition_id = part.id
              LEFT JOIN maasserver_partitiontable AS ptable
                ON part.partition_table_id = ptable.id
              LEFT JOIN maasserver_blockdevice AS ptable_bdev
                ON ptable.block_device_id = ptable_bdev.id
            )
            UPDATE maasserver_filesystem
            SET node_config_id = fs_nodeconfig.node_config_id
            FROM fs_nodeconfig
            WHERE maasserver_filesystem.id = fs_nodeconfig.id
            """
        ),
    ]
