# Generated by Django 2.2.12 on 2022-01-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0257_filesystem_populate_node_config_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesystem",
            name="node",
        ),
        migrations.AlterField(
            model_name="filesystem",
            name="node_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="maasserver.NodeConfig",
            ),
        ),
    ]
