# Generated by Django 2.2.12 on 2022-01-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0258_filesystem_nodeconfig_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="enable_hw_sync",
            field=models.BooleanField(default=False),
        ),
    ]
