# Generated by Django 2.2.12 on 2022-01-28 15:13

from django.db import migrations

SUPPORT_VIEWS = (
    "maas_support__boot_source_cache",
    "maas_support__boot_source_selections",
    "maas_support__commissioning_result_summary",
    "maas_support__configuration__excluding_rpc_shared_secret",
    "maas_support__device_overview",
    "maas_support__ip_allocation",
    "maas_support__license_keys_present__excluding_key_material",
    "maas_support__node_networking",
    "maas_support__node_overview",
)


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0259_add_hardware_sync_flag"),
    ]

    operations = [
        migrations.RunSQL(f"DROP VIEW IF EXISTS {name}")
        for name in SUPPORT_VIEWS
    ]
