# Generated by Django 2.2.12 on 2022-02-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0262_nodeconfig_link_replace_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="primary_rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="maasserver.RackController",
            ),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="secondary_rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="maasserver.RackController",
            ),
        ),
    ]
