# Generated by Django 2.2.12 on 2022-02-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0263_vlan_racks_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedevice",
            name="node_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maasserver.NodeConfig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nodedevice",
            unique_together={
                ("node_config", "bus_number", "device_number", "pci_address")
            },
        ),
    ]
