# Generated by Django 2.2.12 on 2022-02-11 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0264_nodedevice_nodeconfig_link"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE maasserver_nodedevice
            SET node_config_id = maasserver_node.current_config_id
            FROM maasserver_node
            WHERE maasserver_nodedevice.node_id = maasserver_node.id
            """
        ),
    ]
