# Generated by Django 2.2.12 on 2022-02-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0265_nodedevice_nodeconfig_migrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedevice",
            name="node_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="maasserver.NodeConfig",
            ),
        ),
        migrations.RemoveField(
            model_name="nodedevice",
            name="node",
        ),
    ]
