# Generated by Django 2.2.12 on 2022-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0266_nodedevice_unlink_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="sync_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
