# Generated by Django 2.2.12 on 2022-03-22 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0268_partition_index"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX maasserver_interface_node_config_mac_address_idx
            ON maasserver_interface (type, node_config_id, mac_address)
            WHERE (type = 'physical')
            """
        ),
        migrations.RunSQL(
            "DROP INDEX maasserver_interface_type_mac_address_idx"
        ),
    ]
