# Generated by Django 2.2.12 on 2022-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0272_virtualmachine_resources_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticipaddress",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
    ]
