# Generated by Django 2.2.12 on 2022-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0274_audit_log_add_endpoint_cli_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interface",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                through="maasserver.InterfaceRelationship",
                to="maasserver.Interface",
            ),
        ),
    ]
