# Generated by Django 2.2.12 on 2022-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0276_bmc_autodetect_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="authoritative",
            field=models.BooleanField(
                blank=True, db_index=True, default=True, null=True
            ),
        ),
    ]
