# Generated by Django 3.2.12 on 2022-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0277_replace_nullbooleanfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmc",
            name="power_parameters",
            field=models.JSONField(blank=True, default=str, max_length=32768),
        ),
        migrations.AlterField(
            model_name="node",
            name="instance_power_parameters",
            field=models.JSONField(blank=True, default=str, max_length=32768),
        ),
    ]
