# Generated by Django 3.2.12 on 2022-09-01 14:23

from django.db import migrations, models
import django.db.models.deletion

import maasserver.models.cleansave


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0278_generic_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeDeviceVPD",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField()),
                ("value", models.TextField()),
                (
                    "node_device",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maasserver.nodedevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "NodeDeviceVPD",
                "verbose_name_plural": "NodeDeviceVPD",
            },
            bases=(maasserver.models.cleansave.CleanSave, models.Model),
        ),
        migrations.AddIndex(
            model_name="nodedevicevpd",
            index=models.Index(
                fields=["key", "value"], name="maasserver__key_ecce38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nodedevicevpd",
            unique_together={("node_device", "key")},
        ),
    ]
