# Generated by Django 3.2.12 on 2022-09-06 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0279_store_vpd_metadata_for_nodedevice"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE maasserver_node AS node
            SET parent_id = podhints_nodes.node_id
            FROM
              maasserver_bmc AS bmc,
              maasserver_podhints AS podhints,
              maasserver_podhints_nodes AS podhints_nodes
            WHERE
              node.bmc_id = bmc.id AND
              podhints.pod_id = bmc.id AND
              podhints_nodes.podhints_id = podhints.id AND
              node.parent_id is NULL;
            """
        )
    ]
