# Generated by Django 3.2.12 on 2022-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0280_set_parent_for_existing_vms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("path", models.TextField(primary_key=True, serialize=False)),
                ("value", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
