# Generated by Django 3.2.12 on 2022-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0288_rootkey_material_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultSecret",
            fields=[
                ("path", models.TextField(primary_key=True, serialize=False)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
