# Generated by Django 3.2.12 on 2022-12-07 09:16

from django.db import migrations, models


def populate_block_device_type(apps, schema_editor):
    PhysicalBlockDevice = apps.get_model("maasserver", "PhysicalBlockDevice")
    VirtualBlockDevice = apps.get_model("maasserver", "VirtualBlockDevice")
    PhysicalBlockDevice.objects.all().update(device_type="physical")
    VirtualBlockDevice.objects.all().update(device_type="virtual")


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0290_migrate_node_power_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockdevice",
            name="device_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(populate_block_device_type),
    ]
