# Generated by Django 3.2.12 on 2023-01-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0291_rdns_hostnames_as_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootresource",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="bootresourcefile",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="bootsourcecache",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="interface",
            name="ipv4_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="interface",
            name="ipv6_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="interface",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notification",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
