# Generated by Django 3.2.12 on 2023-01-27 07:57

from django.db import migrations, models
import django.db.models.deletion

from maasserver.migrations.spike_interface_ip import MIGRATE_IPS_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0292_use_builtin_json_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterfaceIP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configured", models.BooleanField(editable=False)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maasserver.interface",
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maasserver.staticipaddress",
                    ),
                ),
            ],
            options={
                "db_table": "spike_interface_ip",
            },
        ),
        migrations.RunSQL(MIGRATE_IPS_SQL),
    ]
