# Generated by Django 3.2.12 on 2023-02-27 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0292_use_builtin_json_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(
                help_text="Interface name.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[\\w\\-_.:]+$"
                    )
                ],
            ),
        ),
    ]
