# Generated by Django 3.2.12 on 2023-03-02 12:41

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0294_keyring_data_binary_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interface",
            name="mac_address",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="'%(value)s' is not a valid MAC address.",
                        regex=re.compile(
                            "^([0-9a-fA-F]{1,2}:){5}[0-9a-fA-F]{1,2}$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="neighbour",
            name="mac_address",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="'%(value)s' is not a valid MAC address.",
                        regex=re.compile(
                            "^([0-9a-fA-F]{1,2}:){5}[0-9a-fA-F]{1,2}$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachineinterface",
            name="mac_address",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="'%(value)s' is not a valid MAC address.",
                        regex=re.compile(
                            "^([0-9a-fA-F]{1,2}:){5}[0-9a-fA-F]{1,2}$"
                        ),
                    )
                ],
            ),
        ),
    ]
