# Generated by Django 3.2.12 on 2022-11-17 15:29

from django.db import migrations, models
import django.db.models.deletion

import maasserver.models.cleansave
import metadataserver.fields


class Migration(migrations.Migration):
    dependencies = [
        ("piston3", "0003_piston_nonce_index"),
        ("maasserver", "0295_macaddress_text_field"),
        ("metadataserver", "0035_move_metadata_node_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="NodeKey",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "node",
                            models.OneToOneField(
                                editable=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="maasserver.node",
                            ),
                        ),
                        (
                            "token",
                            models.OneToOneField(
                                editable=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="piston3.token",
                            ),
                        ),
                    ],
                    bases=(
                        maasserver.models.cleansave.CleanSave,
                        models.Model,
                    ),
                ),
                migrations.CreateModel(
                    name="NodeUserData",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("data", metadataserver.fields.BinaryField()),
                        (
                            "node",
                            models.OneToOneField(
                                editable=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="maasserver.node",
                            ),
                        ),
                    ],
                    bases=(
                        maasserver.models.cleansave.CleanSave,
                        models.Model,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
