# Generated by Django 3.2.12 on 2022-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0297_move_metadata_script_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="current_commissioning_script_set",
            field=models.IntegerField(
                blank=True,
                db_column="current_commissioning_script_set_id",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="current_installation_script_set",
            field=models.IntegerField(
                blank=True,
                db_column="current_installation_script_set_id",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="current_testing_script_set",
            field=models.IntegerField(
                blank=True,
                db_column="current_testing_script_set_id",
                null=True,
            ),
        ),
    ]
