# Generated by Django 3.2.12 on 2022-11-21 14:03

from django.db import migrations, models


def clean_up_missing_scriptset_links(apps, schema_editor):
    """Clean up current_foo_script_set_id that have been removed.

    A node points to the current commissioning, installation, and
    testing script set. But since there was no foreign key constraint
    in the database, the corresponding script set might have been removed
    already.
    """
    ScriptSet = apps.get_model("maasserver", "ScriptSet")
    Node = apps.get_model("maasserver", "Node")
    Node.objects.exclude(
        current_testing_script_set__isnull=False,
        current_testing_script_set__in=ScriptSet.objects.all(),
    ).update(current_testing_script_set=None)
    Node.objects.exclude(
        current_commissioning_script_set__isnull=False,
        current_commissioning_script_set__in=ScriptSet.objects.all(),
    ).update(current_commissioning_script_set=None)
    Node.objects.exclude(
        current_installation_script_set__isnull=False,
        current_installation_script_set__in=ScriptSet.objects.all(),
    ).update(current_installation_script_set=None)


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0298_current_script_set_foreign_keys_drop_indexes"),
    ]

    operations = [
        migrations.RunPython(clean_up_missing_scriptset_links),
    ]
