# Generated by Django 3.2.12 on 2023-05-01 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0300_current_script_set_foreign_keys_readd"),
    ]

    operations = [
        migrations.RemoveField(model_name="discovery", name="neighbour"),
        migrations.RemoveField(model_name="discovery", name="mdns"),
        migrations.RemoveField(model_name="discovery", name="observer"),
        migrations.RemoveField(
            model_name="discovery", name="observer_interface"
        ),
        migrations.RemoveField(model_name="discovery", name="fabric"),
        migrations.RemoveField(model_name="discovery", name="vlan"),
        migrations.RemoveField(model_name="discovery", name="subnet"),
    ]
