# Generated by Django 3.2.12 on 2023-05-10 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0302_big_auto_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interface",
            name="ipv4_params",
        ),
        migrations.RemoveField(
            model_name="interface",
            name="ipv6_params",
        ),
        migrations.RunSQL(
            """
            UPDATE maasserver_interface
            SET params = '{}'::jsonb
            WHERE params = '""'::jsonb
            """
        ),
    ]
