# Generated by Django 3.2.12 on 2023-05-10 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0303_interface_params_cleanups"),
    ]

    operations = [
        # drop 'autoconf' parameter
        migrations.RunSQL(
            "UPDATE maasserver_interface SET params = params - 'autoconf'"
        ),
        # convert 'accept_ra' to 'accept-ra'
        migrations.RunSQL(
            """
            UPDATE maasserver_interface
            SET params = (
              params - 'accept_ra' ||
              jsonb_build_object('accept-ra', (params->>'accept_ra')::bool)
            )
            WHERE params->>'accept_ra' IS NOT NULL
            """
        ),
    ]
