# Generated by Django 3.2.12 on 2023-08-23 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0304_interface_params_no_autoconf"),
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA temporal;"),
        migrations.RunSQL("CREATE SCHEMA temporal_visibility;"),
    ]
