# Generated by Django 3.2.12 on 2023-08-31 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0305_add_temporal_schema"),
    ]

    operations = [
        # Set the ephemeral_deploy flag to True if the machine is diskless or the ephemeral_deploy flag was set to True.
        # 1) the machine is not a device
        # 2) the machine is in the statuses [NODE_STATUS.ALLOCATED, NODE_STATUS.DEPLOYING, NODE_STATUS.DEPLOYED,
        # NODE_STATUS.READY]
        # 3) the machine is diskless or the ephemeral_deploy flag was already set to True.
        migrations.RunSQL(
            """
            UPDATE maasserver_node
            SET ephemeral_deploy = subquery.ephemeral_deploy
            FROM (
                WITH storage AS (
                    SELECT 
                        maasserver_node.id AS id, 
                    count(
                      maasserver_physicalblockdevice.blockdevice_ptr_id
                    ) AS disk_count
                    FROM 
                        maasserver_physicalblockdevice 
                            JOIN maasserver_blockdevice ON maasserver_blockdevice.id = maasserver_physicalblockdevice.blockdevice_ptr_id 
                            JOIN maasserver_nodeconfig ON maasserver_nodeconfig.id = maasserver_blockdevice.node_config_id 
                            JOIN maasserver_node ON maasserver_node.id = maasserver_nodeconfig.node_id 
                    GROUP BY 
                        maasserver_node.id
                    ) 
                    SELECT 
                        maasserver_node.id, 
                    CASE WHEN (
                    (
                      maasserver_node.status = 4 
                      OR maasserver_node.status = 6  
                      OR maasserver_node.status = 9  
                      OR maasserver_node.status = 10 
                    ) 
                    AND ( 
                      maasserver_node.ephemeral_deploy 
                      OR storage.disk_count = 0
                    )
                    ) THEN True ELSE False END AS ephemeral_deploy 
                    FROM 
                        maasserver_node 
                    LEFT OUTER JOIN storage ON storage.id = maasserver_node.id
                ) AS subquery
                WHERE maasserver_node.id = subquery.id;
        """
        ),
    ]
