# Generated by Django 3.2.12 on 2023-08-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0307_bootresource_type_drop_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootresourceset",
            name="sync",
            field=models.ManyToManyField(
                blank=True, to="maasserver.RegionController"
            ),
        ),
        migrations.AddField(
            model_name="bootresourcefile",
            name="sha256",
            field=models.CharField(max_length=64, blank=True),
        ),
        migrations.AddField(
            model_name="bootresourcefile",
            name="size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bootresourcefile",
            name="largefile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maasserver.largefile",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE maasserver_bootresourcefile 
            SET sha256 = f.sha256, size = f.total_size
            FROM maasserver_largefile AS f
            WHERE largefile_id = f.id
            """
        ),
    ]
