# Generated by Django 3.2.12 on 2023-09-12 13:31

from django.db import migrations

ROOT_TGZ = "root-tgz"
ROOT_TBZ = "root-tbz"
ROOT_TXZ = "root-txz"

UPLOADED = 2


def rename_uploaded_rootfs_images_sql(filetype, filename):
    return f"""
        UPDATE maasserver_bootresourcefile
        SET filename = '{filename}'
        WHERE
          filetype = '{filetype}'
          AND resource_set_id IN (
            SELECT maasserver_bootresourceset.id FROM maasserver_bootresource
            JOIN maasserver_bootresourceset ON
                maasserver_bootresource.id = maasserver_bootresourceset.resource_id
            WHERE maasserver_bootresource.rtype = {UPLOADED}
          )

    """


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0309_drop_bootloader_filetype"),
    ]

    operations = [
        migrations.RunSQL(
            rename_uploaded_rootfs_images_sql(ROOT_TGZ, "root.tgz")
        ),
        migrations.RunSQL(
            rename_uploaded_rootfs_images_sql(ROOT_TBZ, "root.tbz")
        ),
        migrations.RunSQL(
            rename_uploaded_rootfs_images_sql(ROOT_TXZ, "root.txz")
        ),
    ]
