# Generated by Django 3.2.12 on 2023-10-23 10:30

from django.conf import settings
from django.db import migrations


def maas_worker_user_grant_superuser(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    try:
        user = User.objects.get(username="MAAS", email="maas@localhost")
        user.is_superuser = True
        user.save()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0312_release_script_type"),
    ]

    operations = [migrations.RunPython(maas_worker_user_grant_superuser)]
