# Generated by Django 3.2.12 on 2023-10-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0313_add_superuser_flag_to_existing_sysuser"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bootresourcefile",
            index=models.Index(
                fields=["sha256"], name="maasserver__sha256_f07a8e_idx"
            ),
        ),
    ]
