# Generated by Django 3.2.12 on 2023-11-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0314_bootresourcefile_sha256_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="current_release_script_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maasserver.scriptset",
            ),
        ),
    ]
