# Generated by Django 3.2.12 on 2024-02-26 14:05

from django.db import migrations, models
import django.db.models.deletion

import maasserver.models.cleansave
import maasserver.models.node


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0315_add_current_release_script_set_to_node_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmc",
            name="zone",
            field=models.ForeignKey(
                default=maasserver.models.node.get_default_zone,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="maasserver.zone",
                verbose_name="Physical zone",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="zone",
            field=models.ForeignKey(
                default=maasserver.models.node.get_default_zone,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="maasserver.zone",
                verbose_name="Physical zone",
            ),
        ),
        migrations.AlterField(
            model_name="vmcluster",
            name="zone",
            field=models.ForeignKey(
                default=maasserver.models.node.get_default_zone,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="maasserver.zone",
                verbose_name="Physical zone",
            ),
        ),
        migrations.CreateModel(
            name="DefaultResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="maasserver.zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(maasserver.models.cleansave.CleanSave, models.Model),
        ),
    ]
