# Generated by Django 3.2.12 on 2024-03-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0321_current_script_set_foreign_keys_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="current_commissioning_script_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maasserver.scriptset",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="current_installation_script_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maasserver.scriptset",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="current_testing_script_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maasserver.scriptset",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="current_release_script_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maasserver.scriptset",
            ),
        ),
    ]
