# Generated by Django 3.2.12 on 2024-05-28 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0324_populate_distro_alias"),
        ("maasserver", "0327_foreign_key_readd"),
    ]

    operations = []
