# Generated by Django 3.2.12 on 2024-09-02 15:25

from django.db import migrations, models
from django.db.models import F


def migrate_images(apps, schema_editor):
    BootResourceFile = apps.get_model("maasserver", "BootResourceFile")

    # For the existing images we set the filename_on_disk to the sha256 because we don't want to change the filename of the
    # images that are already on the disk.
    # When the images will be updated, they will move to the new short sha format.
    BootResourceFile.objects.all().update(filename_on_disk=F("sha256"))


class Migration(migrations.Migration):

    dependencies = [
        # depend on the latest patch in the 3.5 branch as this is meant to be
        # backported there.
        ("maasserver", "0327_foreign_key_readd"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootresourcefile",
            name="filename_on_disk",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(migrate_images),
    ]
