# Generated by Django 3.2.12 on 2024-09-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Merge the last 3.5 and master patches
        ("maasserver", "0329_add_reserved_ip_model"),
        ("maasserver", "0330_bootresourcefile_filename_on_disk"),
    ]

    operations = []
