# Generated by Django 3.2.12 on 2024-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0331_merge_322_330"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="enable_kernel_crash_dump",
            field=models.BooleanField(default=False),
        ),
    ]
