# Generated by Django 3.2.12 on 2024-10-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0333_migrate_20_maas_03_machine_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnspublication",
            name="update",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
