# Generated by Django 3.2.12 on 2024-10-18 08:45

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0334_dnspublication_update"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservedip",
            name="maasserver_reservedip_mac_address_vlan_uniq",
        ),
        migrations.AddConstraint(
            model_name="reservedip",
            constraint=models.UniqueConstraint(
                fields=("mac_address", "subnet"),
                name="maasserver_reservedip_mac_address_subnet_uniq",
            ),
        ),
        migrations.RemoveField(
            model_name="reservedip",
            name="vlan",
        ),
        migrations.AlterField(
            model_name="reservedip",
            name="mac_address",
            field=models.TextField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="'%(value)s' is not a valid MAC address.",
                        regex=re.compile(
                            "^([0-9a-fA-F]{1,2}:){5}[0-9a-fA-F]{1,2}$"
                        ),
                    )
                ],
                verbose_name="MAC address",
            ),
        ),
    ]
