# Generated by Django 4.2.11 on 2024-10-22 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0335_reservedip_remove_vlan_update_mac"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bmc",
            name="name-unique",
        ),
    ]
