# Generated by Django 4.2.11 on 2024-12-06 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maasserver", "0336_remove_bmc_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(
                help_text="Interface name.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The interface name must be 1 to 15 characters long and can only contain alphanumeric characters, hyphens ('-'), underscores ('_'), periods ('.'), and colons (':').",
                        regex="^[\\w\\-_.:]{1,15}$",
                    )
                ],
            ),
        ),
    ]
