# Generated by Django 4.2.11 on 2025-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0337_alter_interface_name"),
    ]

    operations = [
        # Add fields to SSHKey
        migrations.AddField(
            model_name="sshkey",
            name="auth_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sshkey",
            name="protocol",
            field=models.CharField(
                blank=True,
                choices=[("lp", "launchpad"), ("gh", "github")],
                max_length=64,
                null=True,
            ),
        ),
    ]
