# Generated by Django 4.2.11 on 2025-01-07 13:02

from django.db import migrations, models


def migrate_keysources_to_sshkeys(apps, schema_editor):
    KeySource = apps.get_model("maasserver", "KeySource")
    SSHKey = apps.get_model("maasserver", "SSHKey")

    for key_source in KeySource.objects.all():
        SSHKey.objects.filter(keysource=key_source).update(
            protocol=key_source.protocol, auth_id=key_source.auth_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0338_add_protocol_sshkey"),
    ]

    operations = [
        migrations.RunPython(migrate_keysources_to_sshkeys),
    ]
