# Generated by Django 4.2.11 on 2025-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0340_drop_keysource_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_dpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_dpu", False),
                    models.Q(("is_dpu", True), ("node_type", 0)),
                    _connector="OR",
                ),
                name="maasserver_node_dpu_is_machine",
            ),
        ),
    ]
