# Generated by Django 4.2.11 on 2025-01-07 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0341_add_is_dpu_to_node"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE alembic_version (version_num VARCHAR(32) NOT NULL);"
        ),
    ]
