# Generated by Django 4.2.11 on 2025-01-07 13:02

from django.db import migrations


class Migration(migrations.Migration):
    """
    Goodbye and thanks for all the fish. DO NOT ADD ANY OTHER DJANGO MIGRATION AFTER THIS ONE!
    """

    dependencies = [
        ("maasserver", "0342_add_alembic_table"),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO alembic_version (version_num) VALUES ('0000');"
        ),
    ]
