# Generated by Django 2.2.12 on 2022-02-17 21:14

from django.db import migrations, models
import django.utils.timezone

import maasserver.models.cleansave


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfTestBuild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "start_ts",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("end_ts", models.DateTimeField(blank=True, null=True)),
                ("git_branch", models.TextField()),
                ("git_hash", models.TextField(unique=True)),
                ("release", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(maasserver.models.cleansave.CleanSave, models.Model),
        ),
    ]
