name: maas-power-driver-raritan
version: '1.0.0'
summary: MAAS power driver for Raritan
description: MAAS power driver for Raritan BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

plugs:
  power-driver:
    interface: content
    content: power-driver
    target: $SNAP_COMMON/power-driver

parts:
  raritan-driver:
    plugin: python
    source: .

  tree:
    plugin: dump
    source: snap/local/tree
