---
title: Lease Propagation Workflow
---
flowchart TD
    A[maas-agent receives a lease] --> B(queue lease in memory)
    B --> C(3 second interval)
    C --> D(agent local activity: send local Go channel message to trigger lease flush)
    D --> E(outside of workflow: flush lease queue and POST data to region, hold onto lease data)
    E --> F(region activity: verify lease with latest data has been persisted)
    F --> G{success?}
    G -->|yes| H(agent local activity: send local Go channel message to drop lease data)
    G -->|no| D
    H --> I[done]
