#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit

# Move to the project root.
cd "$(dirname "$0")/../.."

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

# Run celeryd.
export PYTHONPATH=$PYTHONPATH:`pwd`/src:`pwd`/etc
export CELERY_CONFIG_MODULE=democeleryconfig

# XXX JeroenVermeulen 2012-08-24, bug=1039366: To support multiple workers,
# either pass the --beat only to the master (and make upload_dhcp tasks go
# to all workers) or pass --beat to each worker (and make sure each routes
# scheduled tasks only to itself).
# XXX JeroenVermeulen 2012-08-23, bug=1040529: Use fghack to kludge around
# hanging celery shutdown.
exec fghack "$(type -p celeryd)" -l INFO --beat
