version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - gocritic
    - goheader
    - gosec
    - govet
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - revive
    - staticcheck
    - tagliatelle
    - unused
    - whitespace
    - wsl
    - zerologlint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goheader:
      values:
        regexp:
          YEAR: \d{4}(-\d{4})?
      template: |-
        Copyright (c) {{YEAR}} Canonical Ltd

        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU Affero General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU Affero General Public License for more details.

        You should have received a copy of the GNU Affero General Public License
        along with this program.  If not, see <http://www.gnu.org/licenses/>.
    govet:
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: time-equal
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: context-as-argument
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - staticcheck
        path: internal/
        text: 'ST1000:'
      - linters:
          - revive
        path: internal/
        text: 'package-comments:'
      - linters:
          - revive
        path: internal/
        text: 'exported:'
      - linters:
          - revive
        path: main\.go
        text: 'package-comments:'
      - linters:
          - govet
        path: _test\.go
        text: 'fieldalignment:'
    paths:
      - .*\.my\.go$
      - lib/bad.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
  fix: false
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
  exclusions:
    generated: lax
    paths:
      - .*\.my\.go$
      - lib/bad.go
      - third_party$
      - builtin$
      - examples$
