name: maas-power-driver-seamicro
version: '1.0.0'
summary: MAAS power driver for SeaMicro
description: MAAS power driver for SeaMicro BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

plugs:
  power-driver:
    interface: content
    content: power-driver
    target: $SNAP_COMMON/power-driver

parts:
  seamicro-driver:
    plugin: python
    source: .
