// Code generated by "stringer -type=ServiceStatus -trimprefix=Status"; DO NOT EDIT.

package servicecontroller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusRunning-1]
	_ = x[StatusStopped-2]
	_ = x[StatusError-3]
}

const _ServiceStatus_name = "UnknownRunningStoppedError"

var _ServiceStatus_index = [...]uint8{0, 7, 14, 21, 26}

func (i ServiceStatus) String() string {
	if i < 0 || i >= ServiceStatus(len(_ServiceStatus_index)-1) {
		return "ServiceStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceStatus_name[_ServiceStatus_index[i]:_ServiceStatus_index[i+1]]
}
