#!/bin/bash -e
#
# Copyright 2020 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).
#
#
# Helper to configure a PostgreSQL database for MAAS, and set up the MAAS snap
# accordingly.
#

# shellcheck source=snap/local/tree/helpers/_lib
. /snap/maas/current/helpers/_lib

# minimum supported Ubuntu release
MIN_UBUNTU_RELEASE="18.04"

MAAS_DBPASS=$(random_password)


check_ubuntu_release() {
    if is_version "$(lsb_release -rs)" "<<" "$MIN_UBUNTU_RELEASE"; then
        error_exit "This command must be run on Ubuntu $MIN_UBUNTU_RELEASE or later."
    fi
}

ensure_snap_unused() {
    local current_mode
    current_mode=$(maas_snap_mode)
    [ "$current_mode" != "none" ] || return 0

    cat <<EOF

The MAAS snap is currently configured in "$current_mode" mode.
If you proceed, all existing data in the snap will be destroyed.

EOF
    local answer
    answer=$(ask_yes_no "Proceed?")
    [ "$answer" = "y" ] || exit 0
}

ensure_postgres_installed() {
    ! is_deb_installed postgresql || return 0
    message_step "Installing the PostgreSQL database server..."
    log_to_file apt update -y
    log_to_file apt install -y postgresql
}

pg_user_exists() {
    [ -n "$(pg_query "\du $MAAS_DBUSER")" ]
}

pg_db_exists() {
    [ -n "$(pg_query  "\l $MAAS_DBNAME")" ]
}

setup_database() {
    message_step "Setting up PostgreSQL database for MAAS..."
    ! pg_db_exists || error_exit "
The PostgreSQL database \"$MAAS_DBNAME\" already exists.
Please remove it before running the script.

To connect the MAAS snap to an existing database, run \"maas init\" and provide
details for the database.
"

    if pg_user_exists; then
        cat <<EOF

The PostgreSQL user "$MAAS_DBUSER" already exists.
If you proceed, the password for the user will be updated.

EOF

        local answer
        answer=$(ask_yes_no "Proceed?")
        [ "$answer" = "y" ] || exit 0
    fi

    if pg_user_exists; then
        log_to_file pg_query "ALTER USER \"$MAAS_DBUSER\" WITH ENCRYPTED PASSWORD '$MAAS_DBPASS'"
    else
        log_to_file pg_query "CREATE USER \"$MAAS_DBUSER\" WITH ENCRYPTED PASSWORD '$MAAS_DBPASS'"
    fi
    log_to_file pg_do createdb -O "$MAAS_DBUSER" "$MAAS_DBNAME"

    postgres_update_hba
}

maas_init() {
    cat <<EOF
The MAAS database has been created with the following details:

dbname:   $MAAS_DBNAME
user:     $MAAS_DBUSER
password: $MAAS_DBPASS

If you proceed, MAAS will be configured to run in "region+rack" mode using the
above database configuration.

If you want a different configuration, you can run "maas init" later, and use
the details above for database configuration.

EOF

    local answer
    answer=$(ask_yes_no "Proceed?")
    [ "$answer" = "y" ] || exit 0

    message_step "Initializing MAAS..."
    # prefill some of the questions, remaining ones will be asked to the user
    /snap/bin/maas \
        init \
        --mode region+rack \
        --force \
        --database-host localhost \
        --database-name "$MAAS_DBNAME" \
        --database-user "$MAAS_DBUSER" \
        --database-pass "$MAAS_DBPASS"
}

check_root
check_ubuntu_release
ensure_snap_unused
ensure_postgres_installed
setup_database
maas_init
