#!/bin/bash -e
#
# Copyright 2020 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).
#
#
# Migrates from a .deb-based MAAS install to a snap-based one.
#

# shellcheck source=snap/local/tree/helpers/_lib
. /snap/maas/current/helpers/_lib

# minimum version supported by the migration script
MAAS_MIN_DEB_VERSION="2.4.0"


maas_deb_version() {
    # The version for all MAAS packages is the same, so just grab the first one that
    # is installed
    dpkg-query -W -f'${Version}\n' maas-region-api maas-rack-controller 2>/dev/null \
        | head -n1
}

check_maas_installed() {
    local current_version
    current_version=$(maas_deb_version)
    if [ -z "$current_version" ]; then
        error_exit "No MAAS installation found."
    fi
    if is_version "$current_version" "<<" "$MAAS_MIN_DEB_VERSION"; then
        error_exit "\
This MAAS version is not supported by this migration tool.
Please update MAAS to $MAAS_MIN_DEB_VERSION or later before migrating."
    fi
}

ensure_snap_unused() {
    local current_mode
    current_mode=$(maas_snap_mode)
    [ "$current_mode" != "none" ] || return 0

    cat <<EOF
The MAAS snap is currently configured in "$current_mode" mode.

To proceed with the migration, the snap installation must be cleared.
This will destroy all existing data in the snap.

EOF
    local answer
    answer=$(ask_yes_no "Proceed?")
    [ "$answer" = "y" ] || exit 0

    log_to_file snap stop maas
    rm -rf \
       "$MAAS_SNAP_DATA/var/lib/maas" \
       "$MAAS_SNAP_DATA/root" \
       "$MAAS_SNAP_COMMON/proxy/spool"
}

keep_database() {
    is_deb_installed maas-region-controller || return 0
    rm -f /etc/dbconfig-common/maas-region-controller.conf
    log_to_file debconf-communicate maas-region-controller <<EOF
SET maas-region-controller/dbconfig-remove false
FSET maas-region-controller/dbconfig-remove seen true
EOF
}

migrate_to_snap() {
    message_step "Migrating deb installation to snap"
    log_to_file snap stop maas
    log_to_file "$MAAS_SNAP/bin/maas-deb-migrate"
    log_to_file snap start maas
}

cleanup_debs() {
    message_step "Removing unused deb packages"
    log_to_file apt autoremove -y maas maas-region-api maas-rack-controller
}


check_root
check_maas_installed
ensure_snap_unused
migrate_to_snap
keep_database
cleanup_debs
