# Generated by Django 1.11.11 on 2019-06-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0188_network_testing"),
        ("metadataserver", "0019_add_script_result_suppressed"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="apply_configured_networking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scriptresult",
            name="interface",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maasserver.Interface",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="hardware_type",
            field=models.IntegerField(
                choices=[
                    (0, "Node"),
                    (1, "CPU"),
                    (2, "Memory"),
                    (3, "Storage"),
                    (4, "Network"),
                ],
                default=0,
            ),
        ),
    ]
