# Generated by Django 1.11.11 on 2019-07-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("metadataserver", "0020_network_testing")]

    operations = [
        migrations.AlterField(
            model_name="scriptresult",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Running"),
                    (2, "Passed"),
                    (3, "Failed"),
                    (4, "Timed out"),
                    (5, "Aborted"),
                    (6, "Degraded"),
                    (7, "Installing dependencies"),
                    (8, "Failed installing dependencies"),
                    (9, "Skipped"),
                    (10, "Applying custom network configuration"),
                    (11, "Failed to apply custom network configuration"),
                ],
                default=0,
            ),
        )
    ]
