# Generated by Django 2.2.12 on 2022-05-20 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadataserver", "0027_reorder_machine_resources_script"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scriptset",
            old_name="requested_scripts",
            new_name="tags",
        ),
    ]
