# Generated by Django 3.2.12 on 2022-10-05 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadataserver", "0032_default_auto_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodekey",
            name="key",
        ),
    ]
