# Generated by Django 3.2.12 on 2022-11-17 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadataserver", "0034_use_builtin_json_field"),
        ("maasserver", "0295_macaddress_text_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="NodeKey",
                ),
                migrations.DeleteModel(
                    name="NodeUserData",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="NodeKey",
                    table="maasserver_nodekey",
                ),
                migrations.AlterModelTable(
                    name="NodeUserData",
                    table="maasserver_nodeuserdata",
                ),
            ],
        ),
    ]
