# Generated by Django 3.2.12 on 2022-11-18 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadataserver", "0035_move_metadata_node_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="scriptresult",
                    name="interface",
                ),
                migrations.RemoveField(
                    model_name="scriptresult",
                    name="physical_blockdevice",
                ),
                migrations.RemoveField(
                    model_name="scriptresult",
                    name="script",
                ),
                migrations.RemoveField(
                    model_name="scriptresult",
                    name="script_set",
                ),
                migrations.RemoveField(
                    model_name="scriptresult",
                    name="script_version",
                ),
                migrations.RemoveField(
                    model_name="scriptset",
                    name="node",
                ),
                migrations.DeleteModel(
                    name="Script",
                ),
                migrations.DeleteModel(
                    name="ScriptResult",
                ),
                migrations.DeleteModel(
                    name="ScriptSet",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Script", table="maasserver_script"
                ),
                migrations.AlterModelTable(
                    name="ScriptResult", table="maasserver_scriptresult"
                ),
                migrations.AlterModelTable(
                    name="ScriptSet", table="maasserver_scriptset"
                ),
            ],
        ),
    ]
