"""Create image manifest table

Revision ID: 0009
Revises: 0008
Create Date: 2025-10-22 13:59:58.438358+00:00

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Unlogged means that data is not written in the WAL, so they are faster
    # than ordinary tables, with the drawback of being truncated if a crash occurs.
    # See: https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-UNLOGGED
    op.execute("CREATE UNLOGGED TABLE maasserver_imagemanifest ()")
    op.add_column(
        "maasserver_imagemanifest",
        sa.Column(
            "boot_source_id",
            sa.BigInteger(),
            sa.ForeignKey(
                "maasserver_bootsource.id",
                deferrable=True,
                initially="DEFERRED",
            ),
            nullable=False,
            unique=True,
        ),
    )
    op.add_column(
        "maasserver_imagemanifest",
        sa.Column(
            "manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "maasserver_imagemanifest",
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
    )
    sa.ForeignKeyConstraint(
        ["boot_source_id"],
        ["maasserver_bootsource.id"],
        initially="DEFERRED",
        deferrable=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maasserver_imagemanifest")
    # ### end Alembic commands ###
