#!/bin/bash -x

UTIL_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd)"
RUN_DIR=$UTIL_DIR/../.run

LOCAL_LIB_DIR=$RUN_DIR/var/lib

if [ ! -d "$LOCAL_LIB_DIR" ];
then
    mkdir -p $LOCAL_LIB_DIR
fi

if [ -d "$LOCAL_LIB_DIR/maas" ]
then
    if [ ! -L "$LOCAL_LIB_DIR/maas" ]
    then
        # If .run/var/lib/maas is a directory, it means it was created
        # by our local MAAS service, so we can safely remove it.
        echo "Removing local MAAS dir"
        rm -r $LOCAL_LIB_DIR/maas
    fi
fi
echo "Symlinking .run/var/lib/maas to /var/lib/maas"
sudo ln -sf /var/lib/maas $LOCAL_LIB_DIR/maas
echo "Copying maas-dhcp-helper to /usr/sbin"
sudo cp $UTIL_DIR/../scripts/maas-dhcp-helper /usr/sbin/


authorize_port() {
    port=$1
    sudo touch /etc/authbind/byport/$port
    sudo chown $USER /etc/authbind/byport/$port
    sudo chmod u+x /etc/authbind/byport/$port
}

echo "Allowing $USER to bind to port 53, 68 and 69"
authorize_port $MAAS_TFTP_PORT
authorize_port $MAAS_BIND_PORT
authorize_port 68

echo "Exporting environment variables."
# Make the TFTP and DNS services bind to the privileged ports.
export MAAS_TFTP_PORT=69
export MAAS_BIND_PORT=53

# Make MAAS talk to the installed DHCPD service.
export MAAS_DHCP_CONNECT="1"
