#!/bin/bash

# This script provides a bootable custom Ubuntu image for development purposes

set -e
set -o pipefail

PWD="$(pwd)"
WORK_DIR="$(mktemp -d ./tmp-XXXX)"
OS="${OS:-ubuntu}"
OS_VERSION="${OS_VERSION:-20.04.2}"
IMAGE_TYPE="${IMAGE_TYPE:-live-server}"
OS_ARCH="${OS_ARCH:-amd64}"
BASE_IMAGE_FILE="${BASE_IMAGE_FILE:-${OS}-${OS_VERSION}-${IMAGE_TYPE}-${OS_ARCH}.iso}"
BASE_IMAGE_PATH="${BASE_IMAGE_PATH:-/tmp/${BASE_IMAGE_FILE}}"
BASE_IMAGE_URL="${BASE_IMAGE_URL:-https://releases.ubuntu.com/${OS_VERSION}/${BASE_IMAGE_FILE}}"
BASE_IMAGE_CHECKSUM="${BASE_IMAGE_CHECKSUM:-d1f2bf834bbe9bb43faf16f9be992a6f3935e65be0edece1dee2aa6eb1767423}"
OUTPUT_FILE="custom-${OS}-${OS_VERSION}-${OS_ARCH}.img"
OUTPUT_DIR=/tmp
DISK_SIZE="4G"

pull_image () {
    if [ "${DOWNLOAD_BASE_IMAGE}" -eq "1" ]; then
        echo "Downloading Base Ubuntu Image..."
        curl -L -o "${BASE_IMAGE_PATH}" "${BASE_IMAGE_URL}"
        echo "${BASE_IMAGE_CHECKSUM}  /tmp/${BASE_IMAGE_FILE}" | shasum -c
    fi
}

mount_resources () {
    echo "mounting boot resources"
    mkdir -p "/mnt/${OS}-${OS_VERSION}"
    mount -r "${BASE_IMAGE_PATH}" "/mnt/${OS}-${OS_VERSION}"
}

create_user_data () {
    echo "writing user-data"
    cat > user-data <<EOF
#cloud-config
autoinstall:
    version: 1
    locale: en_US
    user-data:
        disabe_root: false
    keyboard:
        layout: en
        variant: us
    identity:
        hostname: ubuntu-server
        password: "$(mkpasswd --method=SHA-512 --rounds=4096)"
        username: ubuntu
    ssh:
        install-server: true
    storage:
        swap:
            size: 0
        layout:
            name: lvm
    late-commands:
        - mkdir -p /target/curtin
        - touch /target/curtin/curtin-hooks
        - chmod 750 /target/curtin/curtin-hooks
EOF

    touch meta-data
}

create_output_file () {
    if [ ! -e "${OUTPUT_DIR}/${OUTPUT_FILE}" ]; then
        echo "creating output image file"

        truncate -s "${DISK_SIZE}" "${OUTPUT_DIR}/${OUTPUT_FILE}"
    fi
}

build () {
    echo "running build VM"
    kvm -no-reboot -m 2048\
        -nographic\
        -drive file="${OUTPUT_DIR}/${OUTPUT_FILE}",format=raw,cache=none,if=virtio\
        -cdrom "${BASE_IMAGE_PATH}"\
        -kernel "/mnt/${OS}-${OS_VERSION}/casper/vmlinuz"\
        -initrd "/mnt/${OS}-${OS_VERSION}/casper/initrd"\
        -append 'console=ttyS0 autoinstall ds=nocloud-net;s=http://_gateway:3003/'
}

teardown () {
    echo "tearing down workspace"
    kill %1
    umount "/mnt/${OS}-${OS_VERSION}"
    rm -rf "${WORK_DIR}"
}

main () {
    if [ $UID -ne 0 ]; then
        echo "ERROR: Must be run as root!" >&2
        exit 1
    fi

    trap teardown EXIT
    pull_image
    mount_resources
    mkdir -p "${WORK_DIR}/www/"
    cd "${WORK_DIR}/www/"
    create_user_data
    python3 -m http.server 3003 &
    cd ..
    create_output_file
    build
    echo "created image can be found at: ${OUTPUT_DIR}/${OUTPUT_FILE}"
}

main
