#!/usr/bin/env python3
# Copyright 2017 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""
Calculates the version of the snap using git and the version defined in
src/maasserver/__init__.py.
"""

import os
import sys
import subprocess


# Get the path to the repository.
repo_path = os.path.dirname(
    os.path.dirname(os.path.abspath(os.path.realpath(__file__))))

# Get the most recent tag.
recent_tag = subprocess.check_output(
    ['git', '-C', repo_path, 'describe', '--abbrev=0'],
    stderr=subprocess.DEVNULL).decode(sys.getfilesystemencoding()).strip()

# Replace the first '-' with '~' if present.
if '-' in recent_tag:
    recent_tag = '%s~%s' % tuple(recent_tag.split('-', 1))

# Describe number of commits in git.
revno = subprocess.check_output(
    ['git', '-C', repo_path, 'rev-list', '--count', 'HEAD'],
    stderr=subprocess.DEVNULL).decode(sys.getfilesystemencoding()).strip()

# Describe commit hash from git.
commit = subprocess.check_output(
    ['git', '-C', repo_path, 'rev-parse', 'HEAD'],
    stderr=subprocess.DEVNULL).decode(sys.getfilesystemencoding()).strip()

print('%s-%s-g%s-snap' % (recent_tag, revno, commit[:7]))
