#!/usr/bin/env python3
# Copyright 2017 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""
Calculates the version of the snap using git and the version defined in
src/maasserver/__init__.py.
"""

import ast
import os
import sys
import subprocess


# Get the path to the src/maasserver/__init__.py.
repo_path = os.path.dirname(
    os.path.dirname(os.path.abspath(os.path.realpath(__file__))))
init_path = os.path.join(repo_path, 'src', 'maasserver', '__init__.py')

# Get the syntax tree for the file, since we don't want to actually import
# that file into this script.
with open(init_path, 'r') as stream:
    init_ast = ast.parse(stream.read())

# Get the version from the parsed ast tree.
version = None
for node in ast.walk(init_ast):
    if isinstance(node, ast.Assign):
        if node.targets:
            if node.targets[0].id == '__version__':
                version = node.value.s
                break

# Unable to get the version then just set it to 'master'.
if not version:
    version = 'master'

# Describe number of commits in git.
revno = subprocess.check_output(
    ['git', '-C', repo_path, 'rev-list', '--count', 'HEAD'],
    stderr=subprocess.DEVNULL).decode(sys.getfilesystemencoding()).strip()

# Describe commit hash from git.
commit = subprocess.check_output(
    ['git', '-C', repo_path, 'describe', '--abbrev=7', '--always', '--dirty'],
    stderr=subprocess.DEVNULL).decode(sys.getfilesystemencoding()).strip()

print('%s-%s-%s-snap' % (version, revno, commit))
