#!/bin/bash

mkdir -p ~/.buildout/cache

if [ ! -f ~/.buildout/default.cfg ]; then
    cat << EOF > ~/.buildout/default.cfg
[buildout]
download-cache = $HOME/.buildout/cache
eggs-directory = $HOME/.buildout/eggs
EOF
else
    if [ "$1" != "--quiet" ]; then
	    echo "Warning: ~/.buildout/default.cfg already exists."
	    echo "(not overwriting existing configuration)"
    fi
fi

