#!/bin/bash -e
#
# Connect interfaces for the MAAS snap.
#
# This is needed for local installs (`snap try` or ` snap install --dangerous`)
# where autoconnect is not performed.

set -o pipefail

if ! snap connections maas 2>/dev/null; then
    echo "The maas snap is not installed" >&2
    exit 1
fi | \
    awk '$1 != "content" && $3 == "-" {print $2}' | \
    xargs -r -n1 sudo snap connect

# connect content interface too
sudo snap connect maas:maas-cli maas-cli

# need to restart services since some checks are done at startup
sudo snap restart maas
# print out the list of connections
sudo snap connections maas
