#!/bin/bash -e
#
# Connect interfaces for the MAAS snap.
#
# This is needed for local installs (`snap try` or ` snap install --dangerous`)
# where autoconnect is not performed.

set -o pipefail

is_installed() {
    snap connections "$1" >/dev/null 2>&1
}

if ! is_installed maas; then
    echo "The maas snap is not installed" >&2
    exit 1
fi

snap connections maas | \
    awk '$1 != "content" && $3 == "-" {print $2}' | \
    xargs -r -n1 sudo snap connect

# connect content interfaces too
if is_installed maas-test-db; then
    sudo snap connect maas:test-db-socket maas-test-db
fi

# need to restart services since some checks are done at startup
sudo snap restart maas
# print out the list of connections
sudo snap connections maas
