#!/usr/bin/env python3

# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Auto generate builders for domain models.

Generates builder classes in src/maasservicelayer/builders/ for domain models
in src/maasservicelayer/models/ decorated with `@generate_builder`.

Usage:
    @generate_builder
    class User(BaseModel):
        name: str

    $ make generate-builders        # Generate/update builders
    $ make generate-builders-check  # Check if builders need updates

Generation Flow:
    1. Scan domain models with @generate_builder decorator
    2. Scan existing builders using AST to preserve custom methods and imports
       (AST parsing avoids import-time errors when builders reference new fields)
    3. Generate builder classes (fields become FieldType | Unset)
    4. Merge custom code back into generated builders
    5. Write output only if changes detected
    6. Delete builders for removed models

Features:
    - Preserves custom methods and imports in builder classes
    - Automatically manages imports from type annotations
    - Idempotent - only writes when changes detected

Requires Pydantic 2.x and Python 3.10+.
"""

from abc import ABC, abstractmethod
import argparse
import ast
import dataclasses
from datetime import datetime
import importlib
import inspect
import logging
import os
import re
import sys
from types import FunctionType, ModuleType, UnionType
from typing import get_args, get_origin, Self

from pydantic import BaseModel
from pydantic.fields import FieldInfo

logger = logging.getLogger(__name__)

MODELS_PATH = "src/maasservicelayer/models"
BUILDERS_PATH = "src/maasservicelayer/builders"
MODELS_MODULE = "maasservicelayer.models"
BUILDERS_MODULE = "maasservicelayer.builders"

CLASS_TEMPLATE = """

class {model_name}(ResourceBuilder):
    \"\"\"Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    \"\"\"

{fields_definitions}

{builder_methods}

"""

EXCLUDED_FIELDS = ["id"]

# Methods to exclude from extraction when preserving custom builder methods.
# Includes standard Python magic methods, Pydantic/BaseModel methods,
# Python 3.14+ annotation methods, and builder-specific methods.
EXCLUDED_METHODS = {
    "__init__",
    "__new__",
    "__del__",
    "__repr__",
    "__str__",
    "__bytes__",
    "__format__",
    "__lt__",
    "__le__",
    "__eq__",
    "__ne__",
    "__gt__",
    "__ge__",
    "__bool__",
    "__getattr__",
    "__getattribute__",
    "__setattr__",
    "__delattr__",
    "__dir__",
    "__class_getitem__",
    "__mro_entries__",
    "__set_name__",
    "__annotate__",  # Python 3.14+ PEP 649
    "__annotate_func__",  # Python 3.14+ PEP 649
    "to_file",
    "update_methods",
}

MODELS_BASE = "maasservicelayer.models.base"
sys.path.insert(0, "./src")
try:
    base = importlib.import_module(MODELS_BASE)
    Unset = vars(base)["Unset"]
    UNSET = vars(base)["UNSET"]
    ResourceBuilder = vars(base)["ResourceBuilder"]
except KeyError as e:
    print(f"{e} not found in {MODELS_BASE}")
    sys.exit(1)


def default_imports() -> set:
    imports = set()
    imports.add("from pydantic import Field")
    imports.add(
        "from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset"
    )
    return imports


def process_string(s) -> str:
    """Preprocess annotation string representation.

    This function:
        - removes all the not wanted chars in e.g. <class 'x'> and <enum 'x'>
        - translates `NoneType` to `None`
        - removes all modules' prefixes
    """
    s = (
        str(s)
        .removeprefix("<class '")
        .removeprefix("<enum '")
        .removesuffix("'>")
    )
    s = s.replace("NoneType", "None")
    s = re.sub(r"\w*\.", "", s)
    return s


def get_module_name_for_type(type_) -> str:
    if isinstance(type_, str):
        return "builtins"
    module = inspect.getmodule(type_)
    assert module is not None, f"Could not find module for {type_}"
    return module.__name__


def add_imports(module_name: str, field: str, imports: set):
    if module_name not in ["builtins", "types"]:
        if len(module_name.split(".")) >= 1:
            imports.add(f"from {module_name} import {field}")
        else:
            imports.add(f"import {module_name}")


def handle_composite_type(type_, imports: set):
    from typing import Union

    outer = get_origin(type_)
    if outer is UnionType or outer is Union:
        inner = get_args(type_)
        for inner_type in inner:
            if get_origin(inner_type) is not None:
                handle_composite_type(inner_type, imports)
            else:
                handle_simple_type(inner_type, imports)
        return
    module_name = get_module_name_for_type(outer)
    add_imports(module_name, process_string(outer), imports)

    inner = get_args(type_)
    for inner_type in inner:
        if get_origin(inner_type) is not None:
            handle_composite_type(inner_type, imports)
        else:
            handle_simple_type(inner_type, imports)


def handle_simple_type(type_, imports: set):
    module_name = get_module_name_for_type(type_)
    add_imports(module_name, process_string(type_), imports)


def normalize_imports(imports: set) -> set:
    """Normalize and deduplicate imports from the same module.

    Combines multiple imports from the same module into a single statement.
    E.g., ["from x import a", "from x import b"] -> ["from x import a, b"]
    """
    from_imports = {}  # module -> set of items
    other_imports = set()

    for imp in imports:
        if not imp.startswith("from "):
            other_imports.add(imp)
            continue

        parts = imp.split(" import ", 1)
        if len(parts) != 2:
            other_imports.add(imp)
            continue

        module = parts[0].replace("from ", "")
        if module not in from_imports:
            from_imports[module] = set()

        for item in parts[1].split(", "):
            from_imports[module].add(item.strip())

    # Rebuild normalized imports
    normalized = other_imports.copy()
    for module in sorted(from_imports.keys()):
        items = ", ".join(sorted(from_imports[module]))
        normalized.add(f"from {module} import {items}")

    return normalized


def format_annotation(annotation) -> str:
    from typing import Union

    origin = get_origin(annotation)
    if origin is UnionType or origin is Union:
        return " | ".join(
            format_annotation(arg) for arg in get_args(annotation)
        )
    return process_string(str(annotation))


def annotation_contains_unset(annotation) -> bool:
    from typing import Union

    if annotation is Unset:
        return True
    origin = get_origin(annotation)
    if origin is UnionType or origin is Union:
        return any(
            annotation_contains_unset(arg) for arg in get_args(annotation)
        )
    return False


def process_field_annotation(annotation, imports: set) -> str:
    """Process a field annotation and update imports, rendering a |-style union."""
    extract_imports_from_annotation(annotation, imports)
    annotation_str = format_annotation(annotation)
    if annotation_contains_unset(annotation):
        return annotation_str
    return f"{annotation_str} | Unset"


def extract_imports_from_annotation(annotation, imports: set):
    """Extract imports from a type annotation."""
    if get_origin(annotation) is not None:
        handle_composite_type(annotation, imports)
    else:
        handle_simple_type(annotation, imports)


@dataclasses.dataclass(kw_only=True)
class GenericModel(ABC):
    name: str
    fields: dict[str, FieldInfo]
    model_imports: set = dataclasses.field(default_factory=default_imports)


@dataclasses.dataclass(kw_only=True)
class GenericModule[T](ABC):
    filename: str
    models: list[T]
    module_imports: set = dataclasses.field(default_factory=default_imports)

    @classmethod
    @abstractmethod
    def from_file(cls, module: ModuleType, filename: str) -> Self:
        pass


@dataclasses.dataclass(kw_only=True)
class GenericCollection[M](ABC):
    modules: list[M]
    module_prefix: str

    @classmethod
    @abstractmethod
    def from_path(cls, path: str) -> Self:
        pass

    def pop_module_with_filename(self, filename: str) -> M | None:
        for i, m in enumerate(self.modules):
            if m.filename == filename:
                return self.modules.pop(i)
        return None

    def __iter__(self):
        for module in self.modules:
            yield module

    def __len__(self):
        return len(self.modules)


@dataclasses.dataclass(kw_only=True)
class BuilderModel(GenericModel):
    methods: list[tuple[str, FunctionType]] = dataclasses.field(
        default_factory=list
    )

    def to_file(self) -> str:
        output = self.get_output()
        # Update model_imports for side effect (used by BuilderModule.to_file)
        imports = self.model_imports.copy()
        for field_name in self.fields.keys():
            field_info = self.fields[field_name]
            process_field_annotation(field_info.annotation, imports)
        self.model_imports = imports
        return output

    def update_methods(self, methods):
        self.methods = methods

    def __eq__(self, other) -> bool:
        """Compare the fields to check if the two models differ."""
        if isinstance(other, BuilderModel):
            if self.name != other.name:
                return False
            if set(self.fields.keys()) != set(other.fields.keys()):
                return False
            for field_name in self.fields:
                if (
                    self.fields[field_name].annotation
                    != other.fields[field_name].annotation
                ):
                    return False
            return True
        return False

    def get_output(self) -> str:
        """Generate the class definition output."""
        field_lines = ""
        imports = self.model_imports.copy()

        for field_name in sorted(self.fields.keys()):
            field_info = self.fields[field_name]
            annotation_str = process_field_annotation(
                field_info.annotation, imports
            )
            field_lines += (
                f"    {field_name}: {annotation_str} = Field(default=UNSET)\n"
            )

        method_lines = ""
        for method_item in self.methods:
            # Handle both (name, source_code) and (name, method_obj) formats
            if isinstance(method_item[1], str):
                # Source code string
                method_lines += method_item[1] + "\n"
            else:
                # Method object
                method_obj = method_item[1]
                if method_obj is not None:
                    method_lines += "".join(
                        inspect.getsourcelines(method_obj)[0]
                    )

        return CLASS_TEMPLATE.format(
            model_name=self.name,
            fields_definitions=field_lines,
            builder_methods=method_lines,
        )


@dataclasses.dataclass(kw_only=True)
class BuilderModule(GenericModule[BuilderModel]):
    source_methods: dict[str, list[tuple[str, str]]] = dataclasses.field(
        default_factory=dict
    )
    source_imports: set = dataclasses.field(default_factory=set)
    file_header: str = ""

    @classmethod
    def from_file(cls, module: ModuleType, filename: str):
        # Extract file header (copyright and comments before imports)
        filepath = os.path.join(BUILDERS_PATH, filename)
        file_header = ""
        try:
            with open(filepath, "r") as f:
                lines = []
                for line in f:
                    # Stop at first non-comment, non-blank line (usually an import)
                    if line.strip() and not line.startswith("#"):
                        break
                    lines.append(line)
                file_header = "".join(lines).rstrip("\n") + "\n\n"
        except FileNotFoundError:
            pass  # New file, use default header

        # Extract methods from source code to avoid import-time failures

        models = []
        try:
            model_classes = inspect.getmembers(
                module,
                lambda x: (
                    inspect.isclass(x) and inspect.getmodule(x) == module
                ),
            )
            for name, class_ in model_classes:
                if name.endswith("Builder") and name != "ResourceBuilder":
                    builder_methods = inspect.getmembers(
                        class_,
                        lambda x: (
                            (inspect.isfunction(x) or inspect.ismethod(x))
                            and not getattr(ResourceBuilder, x.__name__, False)
                            and not getattr(BaseModel, x.__name__, False)
                            and x.__name__ not in EXCLUDED_METHODS
                        ),
                    )
                    fields = {
                        k: v
                        for k, v in class_.model_fields.items()
                        if k not in EXCLUDED_FIELDS
                    }
                    models.append(
                        BuilderModel(
                            name=name,
                            fields=fields,
                            methods=builder_methods,
                        )
                    )
        except Exception:
            # If import fails, extract methods from source code instead
            source_methods_dict, _ = extract_source_methods_and_imports(
                filepath
            )
            for class_name, methods_list in source_methods_dict.items():
                if (
                    class_name.endswith("Builder")
                    and class_name != "ResourceBuilder"
                ):
                    # Convert source code methods to tuples of (name, source)
                    models.append(
                        BuilderModel(
                            name=class_name,
                            fields={},
                            methods=methods_list,
                        )
                    )
        return cls(filename=filename, models=models, file_header=file_header)

    def to_file(self) -> str:
        """Generate the complete file output."""
        return self.get_output()

    def update_models_methods_from_other(self, other):
        if self.filename != other.filename:
            raise Exception("Cannot update models of different modules.")
        models_self = sorted(self.models, key=lambda m: m.name)
        models_other = sorted(other.models, key=lambda m: m.name)
        for model, other_model in zip(models_self, models_other, strict=False):
            model.update_methods(other_model.methods)
        # Preserve source methods, imports, and file header from existing builder
        self.source_methods = other.source_methods
        self.source_imports = other.source_imports
        self.file_header = other.file_header

    def __eq__(self, other) -> bool:
        models_self = sorted(self.models, key=lambda m: m.name)
        models_other = sorted(other.models, key=lambda m: m.name)
        if len(models_self) != len(models_other):
            return False
        for m1, m2 in zip(models_self, models_other, strict=False):
            if m1 != m2:
                return False
        return True

    def get_output(self) -> str:
        """Generate the complete file output."""
        class_defs = ""
        module_imports = self.module_imports.copy()

        for class_ in self.models:
            if class_.name in self.source_methods:
                class_.methods = self.source_methods[class_.name]

            class_defs += class_.to_file()
            module_imports = module_imports | class_.model_imports

        module_imports |= self.source_imports
        # Filter out unused Union import (we now use PEP 604 syntax)
        module_imports = {
            imp for imp in module_imports if imp != "from typing import Union"
        }
        module_imports = normalize_imports(module_imports)

        imports = "\n".join(sorted(module_imports))
        # Use preserved file header or generate default
        if self.file_header:
            header = self.file_header
        else:
            current_year = datetime.now().year
            header = f"# Copyright {current_year} Canonical Ltd.  This software is licensed under the\n"
            header += "# GNU Affero General Public License version 3 (see the file LICENSE).\n\n"
        header += imports + "\n\n"
        return header + class_defs

    def _normalize_ast(self, tree: ast.Module) -> ast.Module:
        """Normalize AST by sorting imports to ignore import order differences."""
        # Separate imports from other statements
        imports = []
        other_stmts = []

        for node in tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                imports.append(node)
            else:
                other_stmts.append(node)

        # Sort imports by module name for consistent comparison
        def import_key(node):
            if isinstance(node, ast.Import):
                return node.names[0].name
            elif isinstance(node, ast.ImportFrom):
                return node.module or ""
            return ""

        imports.sort(key=import_key)

        # Reconstruct tree with sorted imports
        tree.body = imports + other_stmts
        return tree

    def outputs_match(self, other: "BuilderModule") -> bool:
        """Check if two modules would generate identical output.

        Compares AST representations to ignore formatting differences while
        detecting substantive code changes like invalid Field() parameters.
        """
        if not isinstance(other, BuilderModule):
            return False

        # Compare against actual file content on disk using AST comparison
        # This catches substantive differences (e.g., required=False) while
        # ignoring formatting differences introduced by ruff
        try:
            filepath = os.path.join(BUILDERS_PATH, self.filename)
            with open(filepath, "r") as f:
                existing_content = f.read()

            generated_output = self.get_output()

            # Parse both as AST and compare with normalized imports
            try:
                existing_tree = self._normalize_ast(
                    ast.parse(existing_content)
                )
                generated_tree = self._normalize_ast(
                    ast.parse(generated_output)
                )
                return ast.dump(existing_tree) == ast.dump(generated_tree)
            except SyntaxError:
                # If either has syntax errors, fall back to string comparison
                return generated_output == existing_content

        except FileNotFoundError:
            # File doesn't exist yet, compare generated outputs
            return self.get_output() == other.get_output()


def extract_source_methods_and_imports(
    filepath: str,
) -> tuple[dict[str, list[tuple[str, str]]], set]:
    """Extract custom methods and imports from a builder source file without importing it.

    Returns (methods_dict, imports_set) where methods_dict maps class names to lists of
    (method_name, source_code) tuples.

    This uses AST parsing to avoid import-time failures when builder files have
    references to newly added fields or other incompatibilities with the current
    environment. Exceptions are logged but not raised; incomplete extraction is
    preferred over generation failure.
    """
    methods_by_class = {}
    imports = set()

    try:
        with open(filepath, "r") as f:
            content = f.read()

        tree = ast.parse(content)
        lines = content.splitlines(keepends=True)

        # Extract imports
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(
                        f"import {alias.name} as {alias.asname}"
                        if alias.asname
                        else f"import {alias.name}"
                    )
            elif isinstance(node, ast.ImportFrom):
                module = node.module or ""
                names = ", ".join(
                    f"{a.name} as {a.asname}" if a.asname else a.name
                    for a in node.names
                )
                imports.add(f"from {module} import {names}")

        # Extract methods from classes
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                class_methods = []
                seen_methods = set()
                for item in node.body:
                    if isinstance(
                        item, (ast.FunctionDef, ast.AsyncFunctionDef)
                    ):
                        if (
                            item.name not in EXCLUDED_METHODS
                            and item.name not in seen_methods
                        ):
                            seen_methods.add(item.name)
                            start_line = (
                                item.decorator_list[0].lineno - 1
                                if item.decorator_list
                                else item.lineno - 1
                            )
                            source = "".join(
                                lines[start_line : item.end_lineno]
                            )
                            class_methods.append((item.name, source))
                if class_methods:
                    methods_by_class[node.name] = class_methods
    except Exception as e:
        logger.debug(
            f"Failed to extract methods/imports from {filepath}: {e}. "
            "Will regenerate without preserving custom code."
        )

    return methods_by_class, imports


@dataclasses.dataclass(kw_only=True)
class BuilderCollection(GenericCollection[BuilderModule]):
    module_prefix: str = BUILDERS_MODULE

    @classmethod
    def from_path(cls, path: str):
        modules = []
        for filename in os.listdir(path):
            modulename = f"{cls.module_prefix}.{filename.removesuffix('.py')}"
            filepath = os.path.join(BUILDERS_PATH, filename)
            source_methods, source_imports = (
                extract_source_methods_and_imports(filepath)
            )

            try:
                module = importlib.import_module(modulename)
                builder_module = BuilderModule.from_file(module, filename)
            except Exception as e:
                # If import fails, create an empty builder module and log for debugging.
                # This is intentional fault-tolerance: AST parsing may preserve some code
                # even if the builder file cannot be imported due to forward references
                # or other compatibility issues.
                logger.debug(
                    f"Failed to import builder module {modulename}: {e}. "
                    "Proceeding with AST-extracted methods only."
                )
                builder_module = BuilderModule(filename=filename, models=[])

            # Store source methods and imports for later use
            builder_module.source_methods = source_methods
            builder_module.source_imports = source_imports

            if len(builder_module.models) == 0:
                continue
            modules.append(builder_module)
        return cls(modules=modules)

    def __contains__(self, filename: str):
        for m in self.modules:
            if m.filename == filename:
                return True
        return False


@dataclasses.dataclass(kw_only=True)
class DomainModel(GenericModel):
    def to_builder(self) -> BuilderModel:
        imports = default_imports()

        for field_info in self.fields.values():
            extract_imports_from_annotation(field_info.annotation, imports)

        return BuilderModel(
            name=f"{self.name}Builder",
            fields=self.fields,
            model_imports=imports,
        )


@dataclasses.dataclass(kw_only=True)
class DomainModule(GenericModule[DomainModel]):
    @classmethod
    def from_file(cls, module: ModuleType, filename: str):
        model_classes = inspect.getmembers(
            module,
            lambda x: (
                getattr(x, "__generate_builder__", False)
                and inspect.getmodule(x) == module
            ),
        )
        models = []
        for name, class_ in model_classes:
            fields = {
                k: v
                for k, v in class_.model_fields.items()
                if k not in EXCLUDED_FIELDS
            }
            models.append(DomainModel(name=name, fields=fields))

        return cls(filename=filename, models=models)

    def to_builder_module(self) -> BuilderModule:
        builders = []
        for model in self.models:
            builders.append(model.to_builder())
        return BuilderModule(filename=self.filename, models=builders)


@dataclasses.dataclass(kw_only=True)
class DomainCollection(GenericCollection[DomainModule]):
    module_prefix: str = MODELS_MODULE

    @classmethod
    def from_path(cls, path: str):
        modules = []
        for filename in os.listdir(path):
            modulename = f"{cls.module_prefix}.{filename.removesuffix('.py')}"
            module = importlib.import_module(modulename)
            domain_module = DomainModule.from_file(module, filename)
            if len(domain_module.models) == 0:
                continue
            modules.append(domain_module)
        return cls(modules=modules)


def write_builder_file(filename: str, data: str):
    with open(f"{BUILDERS_PATH}/{filename}", "w") as f:
        f.write(data)


def delete_builder_file(filename: str):
    os.remove(f"{BUILDERS_PATH}/{filename}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--check", action="store_true")
    args = parser.parse_args()

    domain_collection = DomainCollection.from_path(MODELS_PATH)
    builder_collection = BuilderCollection.from_path(BUILDERS_PATH)

    to_write = {}
    to_delete = []

    for domain_module in domain_collection:
        generated_builder_module = domain_module.to_builder_module()
        filename = generated_builder_module.filename
        existing_builder_module = builder_collection.pop_module_with_filename(
            filename
        )

        if existing_builder_module is None:
            to_write[filename] = generated_builder_module.to_file()
        else:
            # Always update with existing methods first
            generated_builder_module.update_models_methods_from_other(
                existing_builder_module
            )
            # Now check if the output would be the same
            if not generated_builder_module.outputs_match(
                existing_builder_module
            ):
                to_write[filename] = generated_builder_module.to_file()

    for module in builder_collection:
        to_delete.append(module.filename)

    if args.check:
        if to_write or to_delete:
            if to_write:
                print(
                    f"Builders {list(to_write.keys())} must be re-generated."
                )
            if to_delete:
                print(f"Builders {to_delete} must be deleted.")
            print("Run `make generate-builders`.")
            sys.exit(1)
    else:
        for file, data in to_write.items():
            write_builder_file(file, data)
        for file in to_delete:
            delete_builder_file(file)


if __name__ == "__main__":
    main()
