#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Copying /usr/lib/maas/maas-dhcp-monitor..."
sudo mkdir -p /usr/lib/maas
sudo cp "$SCRIPT_DIR/../scripts/maas-dhcp-monitor" /usr/lib/maas/maas-dhcp-monitor
SUDOERS_LINE="$USER ALL= NOPASSWD: /usr/lib/maas/maas-dhcp-monitor"
SUDOERS_FILE=/etc/sudoers.d/99-maas-dev-$USER
echo "Installing sudoers file: $SUDOERS_FILE"
echo "$SUDOERS_LINE" | sudo tee $SUDOERS_FILE
sudo chmod 440 $SUDOERS_FILE
echo "Done. You should now be able to do the following to get raw 'tcpdump' output:"
echo "    sudo /usr/lib/maas/maas-dhcp-monitor <interface>"
echo "In addition, the following command should now work in the dev env:"
echo "    bin/maas-rack observe-dhcp <interface>"
