#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Copying /usr/lib/maas/maas-network-monitor..."
sudo mkdir -p /usr/lib/maas
sudo cp "$SCRIPT_DIR/../scripts/maas-network-monitor" /usr/lib/maas/maas-network-monitor
echo "Copying /usr/lib/maas/maas-dhcp-monitor..."
sudo cp "$SCRIPT_DIR/../scripts/maas-dhcp-monitor" /usr/lib/maas/maas-dhcp-monitor
echo "Copying /usr/lib/maas/maas-beacon-monitor..."
sudo cp "$SCRIPT_DIR/../scripts/maas-beacon-monitor" /usr/lib/maas/maas-beacon-monitor

SUDOERS_FILE=/etc/sudoers.d/99-maas-dev-$USER

echo "Installing sudoers file: $SUDOERS_FILE"
cat << EOF | sudo tee $SUDOERS_FILE
$USER ALL= NOPASSWD: /usr/lib/maas/maas-network-monitor
$USER ALL= NOPASSWD: /usr/lib/maas/maas-dhcp-monitor
$USER ALL= NOPASSWD: /usr/lib/maas/maas-beacon-monitor
EOF
sudo chmod 440 $SUDOERS_FILE

echo ""
echo "Done. You should now be able to run the following to get raw 'tcpdump' output:"
echo "    sudo /usr/lib/maas/maas-network-monitor <interface>"
echo "    sudo /usr/lib/maas/maas-dhcp-monitor <interface>"
echo "    sudo /usr/lib/maas/maas-beacon-monitor <interface>"
echo ""
echo "In addition, the following commands should now work in the dev env:"
echo "Done. You should now be able to do the following to get raw 'tcpdump' output:"
echo "    sudo /usr/lib/maas/maas-dhcp-monitor <interface>"
echo "In addition, the following command should now work in the dev env:"
echo "    bin/maas-rack observe-arp <interface>"
echo "    bin/maas-rack observe-dhcp <interface>"
echo "    bin/maas-rack observe-beacons <interface>"


