#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"/..

# This script checks to see if the JavaScript code needs to be rebuilt, based
# on whether or not any *.js files, package.json, or yarn.lock appear in the
# output of `git status`.
# The --porcelain option is used to ensure that the output of 'git status' is
# expected to be formatted for use by scripts, and is consistent over time.

git status --porcelain=v2 \
    | cut -d' ' -f9- \
    | egrep -q '\.js$|package\.json$|yarn\.lock$'

exit $?
