#!/bin/bash

TMPFILE=$(mktemp)
cd $(dirname $0)
PSQL_ARGS="maasdb"
SUDO_ARGS="sudo -u postgres"

# Detect a development environment
if [ -d ../db -a -f ../HACKING.txt ]; then
    echo "Using development database."
    cd ..
    SUDO_ARGS=""
    PSQL_ARGS="-h $(pwd)/db maas"
fi

function cleanup {
    rm -f $TMPFILE
}
trap cleanup EXIT

cat <<EOF > $TMPFILE
\pset pager off


SELECT * FROM maas_support__node_overview;
SELECT * FROM maas_support__device_overview;
SELECT * FROM maas_support__node_networking;
SELECT * FROM maas_support__boot_source_selections;
SELECT * FROM maas_support__boot_source_cache;
SELECT * FROM maas_support__configuration__excluding_rpc_shared_secret;
SELECT * FROM maas_support__license_keys_present__excluding_key_material;
SELECT * FROM maas_support__ssh_keys__by_user;
SELECT * FROM maas_support__commissioning_result_summary;
SELECT ip, mac_address, hostname, last_seen, observer_hostname,
    observer_interface_name
    FROM maasserver_discovery
    ORDER BY last_seen DESC;
SELECT * FROM maasserver_mdns ORDER BY ip;
SELECT * FROM maasserver_neighbour ORDER BY ip;

EOF

chmod o+r $TMPFILE

cd /tmp
$SUDO_ARGS psql $PSQL_ARGS -e -f $TMPFILE 2>&1
