#!/bin/bash

SCRIPT_PATH="$(realpath "$(dirname "$0")")"

maas_version() {
    local repo_path="$SCRIPT_PATH/.."
    local version
    # need the full path, otherwise the python from the stage area is used when
    # run inside a snap.
    version=$(/usr/bin/python3 "$repo_path/setup.py" --version)

    if [ -n "$SNAPCRAFT_PART_SRC" ]; then
        # for the snap, just return the package version
        echo "$version"
    else
        # return a deb-compatible version
        echo "$version" | \
            sed 's/\.dev/~dev/; s/a/~alpha/; tend; s/b/~beta/; tend; s/rc/~rc/; :end'
    fi
}

# need the full path, otherwise the python from the stage area is used when run
# inside a snap.  Also, replace the first - with a ~ for debian version
# compatibility.
VERSION=$(maas_version)
GIT_REF=HEAD
GIT_HASH=$(git rev-parse --short "$GIT_REF")
GIT_REV_COUNT=$(git rev-list --count "$GIT_REF")

echo "${VERSION}-${GIT_REV_COUNT}-g.${GIT_HASH}"
