#!/bin/bash

SCRIPT_PATH="$(realpath "$(dirname "$0")")"

# Return a Debian-compatible version from the Python version
to_debian() {
    sed 's/a/~alpha/; tend; s/b/~beta/; tend; s/rc/~rc/; :end'
}

maas_version() {
    # need the full path, otherwise the python from the stage area is used when
    # run inside a snap.
    /usr/bin/python3 "$SCRIPT_PATH/../setup.py" --version | to_debian
}

# need the full path, otherwise the python from the stage area is used when run
# inside a snap.  Also, replace the first - with a ~ for debian version
# compatibility.
VERSION=$(maas_version)
GIT_REF=HEAD
GIT_HASH=$(git rev-parse --short "$GIT_REF" || echo "0000000000" )
GIT_REV_COUNT=$(git rev-list --count "$GIT_REF" || echo "0")

echo "${VERSION}-${GIT_REV_COUNT}-g.${GIT_HASH}"
