#!/bin/bash -e

errors=0
if [ -z "$DEBEMAIL" ]; then
    echo '[!] Set your $DEBEMAIL to an e-mail address matching your GPG key.' 1>&2
    let errors=$errors+1
fi

if [ -z "$DEBNAME" ]; then
    echo '[!] Set your $DEBNAME to your full name.' 1>&2
    let errors=$errors+1
fi

if [ $errors -gt 0 ]; then
    exit 1
fi

MISSING=""
if [ ! -x /usr/bin/pbuilder-dist ]; then
    MISSING="$MISSING ubuntu-dev-tools"
fi

if [ ! -x /usr/bin/dpkg-scanpackages ]; then
    MISSING="$MISSING dpkg-dev"
fi

if [ ! -x /usr/bin/dpkg-sig ]; then
    MISSING="$MISSING dpkg-sig"
fi

if [ "$MISSING" != "" ]; then
    sudo apt-get install -yu $MISSING
fi


# MAAS doesn't support building on Trusty, so don't bother with it.
DISTRIBUTIONS="$(distro-info --supported | grep -v trusty)"

PBUILDFOLDER=${PBUILDFOLDER:-$HOME/pbuilder}

for distro in $DISTRIBUTIONS; do
    if [ -f $PBUILDFOLDER/$distro-base.tgz ]; then
        pbuilder-dist $distro update
    else
        pbuilder-dist $distro create
    fi
done

