#!/bin/bash

ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$ROOTDIR"

rm -rf build_pkg
rm -rf ~/pbuilder/*_result
rm -rf ~/pbuilder/archive

utilities/release-build --bionic
utilities/create-deb-repo --bionic
