#!/bin/bash -e

ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$ROOTDIR"
BUILDDIR=$ROOTDIR/build_pkg
if [ ! -d $BUILDDIR ]; then
    mkdir $BUILDDIR
fi

usage () {
    DISTRO_ARGS=$(distro-info --supported | sed 's/^/[--/g' | sed 's/$/]/' | tr '\n' ' ')
    echo "Usage:"
    echo "    $0 $DISTRO_ARGS \\"
    echo "       [--keep-changelog] [commit (defaults to HEAD)]"
    exit 1
}

DEFAULT_DISTROS="$(ubuntu-distro-info --supported | grep -v trusty)"
PACKAGE_DISTROS=""
KEEP_CHANGELOG=0

for arg in "$@"; do
    if [ "$arg" = "-h" -o "$arg" = "--help" ]; then
        usage
    fi
    if echo "$arg" | grep -q "^--"; then
        option="$(echo "$arg" | sed 's/^--//')"
        if [ "$option" = "keep-changelog" ]; then
            KEEP_CHANGELOG=1
        fi
        if echo $DEFAULT_DISTROS | grep -q $option; then
            PACKAGE_DISTROS="$PACKAGE_DISTROS $option"
        fi
        shift
    fi
done

if [ "$PACKAGE_DISTROS" = "" ]; then
    PACKAGE_DISTROS="$DEFAULT_DISTROS"
fi

if [ -z "$1" ]; then
    echo "WARNING: No commit specified, using HEAD instead"
    COMMIT="HEAD"
else
    COMMIT="$1"
fi

function cleanup {
    # Revert any unstaged temporary changes to the changelog.
    cd "$ROOTDIR"
    if [ $KEEP_CHANGELOG -eq 0 ]; then
        git checkout -- debian/changelog
    fi
}
trap cleanup EXIT

# Ensure the maintainer e-mail address is set, so that signing works properly.
dch -a "" --release-heuristic log --nomultimaint

PKG=$(head -n1 debian/changelog | awk '{print $1}')
MAJOR_VER=$(head -n 1 debian/changelog | sed 's/^.*(//' | sed 's/).*//' | sed 's/-.*//')
REV_COUNT=$(git rev-list --count $COMMIT)
REV_SHORT=$(git rev-parse --short $COMMIT)
FULL_VER="$MAJOR_VER-$REV_COUNT-g$REV_SHORT"
TARBALL="maas_$FULL_VER.orig.tar.gz"

get_orig_source() {
        git archive --format=tar.gz --prefix="${PKG}-${FULL_VER}.orig/" ${COMMIT} -o ${TARBALL}

}
# Obtain the tarball from a local branch
get_orig_source

# Copy the tarball to the local dir
mv "${TARBALL}" "$BUILDDIR"

# Update the changelog
sed -i "s/${MAJOR_VER}-0ubuntu1/${FULL_VER}-0ubuntu1/i" debian/changelog

# Untar
cd $BUILDDIR
tar zxvf ${PKG}_${FULL_VER}.orig.tar.gz
cd "${PKG}-${FULL_VER}.orig/"
cp -r $ROOTDIR/debian .

if echo "$PACKAGE_DISTROS" | grep -q "bionic"; then
    cp $ROOTDIR/debian/changelog debian/changelog
    sed -i "s/) UNRELEASED;/~18.04.1) bionic;/i" debian/changelog
    debuild -S -sa
fi
