#!/bin/bash -e
#
# Prepare a MAAS release by doing the following:
#
# - update python project version
# - add d/changelog entry for the release
# - commit changes and tag commit with release tag
#
# The script must be called with a single argument for the MAAS python version
# to update to.
#

SCRIPT="$(basename "$0")"
MAAS_PATH="$(realpath "$(dirname "$0")/../")"

exit_error() {
    echo "$@" >&2
    exit 1
}

git_tree_clean() {
    git diff-index --quiet HEAD
}

deb_version() {
    local version
    version="$(echo "$1" | sed 's/a/~alpha/; tend; s/b/~beta/; tend; s/rc/~rc/; :end')"
    epoch="$(head -1 "${MAAS_PATH}/debian/changelog" | sed -n 's|maas (\([1-9]*\):.*|\1|p')"
    if [ -n "$epoch" ]; then
	echo "${epoch}:${version}-0ubuntu1"
    else
	echo "${version}-0ubuntu1"
    fi
}

verbose_version() {
    echo "$1" | sed 's/a/ alpha/; tend; s/b/ beta/; tend; s/rc/ RC/; :end'
}

tag_version() {
    echo "$1" | sed 's/a/-alpha/; tend; s/b/-beta/; tend; s/rc/-rc/; :end'
}

replace_setup_version() {
    local version="$1"
    sed -i 's/\bversion=".*$/version="'"$version"'",/' setup.py
}

add_debian_changelog() {
    local version="$1"
    dch -v "$(deb_version "$version")" \
        "New upstream release, MAAS $(verbose_version "$version")."
    dch -r ""
}

commit_and_tag() {
    local version="$1"
    local message
    message="Release $(verbose_version "$version")"

    git commit -a -m "$message"
    git tag -a "$(tag_version "$version")" -m "$message"
}

version="$1"

if [ -z "$version" ]; then
    exit_error "Usage $SCRIPT <MAJOR>.<MINOR>.<MICRO>(a<num>|b<num>|rc<num>)"
elif ! echo "$version" | grep -Eq "^[2-9]+\.[0-9]+\.[0-9]+((a|b|rc)[0-9]+)?$"; then
    echo "Invalid version!" >&2
    exit_error "Usage $SCRIPT <MAJOR>.<MINOR>.<MICRO>(a<num>|b<num>|rc<num>)"
fi

if ! git_tree_clean; then
    exit_error "Git tree is not clean, please reset."
fi

replace_setup_version "$version"
add_debian_changelog "$version"
commit_and_tag "$version"
