#!/bin/bash -e
#
# Helpers to run performance tests in CI.

set -o pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cd "${SCRIPT_DIR}/.." || exit 1

GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
GIT_HASH="$(git rev-parse HEAD)"

PYTHONHASHSEED="${PYTHONHASHSEED:-$(shuf -i 0-4294967295 -n 1)}"
MAAS_RAND_SEED="${MAAS_RAND_SEED:-$(od -vAn -N8 -tx8 < /dev/urandom | tr -d ' ')}"

DB_DUMP=$1
OUTPUT_DIR="perf-tests-out"
OUTPUT_FILE="${OUTPUT_FILE:-maas-perf-results.json}"

if [ -z "$1" ]
then
  echo "Usage: $0 <maas_db_dump>"
  exit 1
fi

export MAAS_RAND_SEED PYTHONHASHSEED GIT_HASH GIT_BRANCH

echo "MAAS_RAND_SEED=${MAAS_RAND_SEED}"
echo "PYTHONHASHSEED=${PYTHONHASHSEED}"

bin/pytest \
    -v \
    --junit-xml=junit-perf.xml \
    --maas-recreate-initial-db \
    --maas-initial-db "${DB_DUMP}" \
    --perf-output-dir "$OUTPUT_DIR" \
    ./src/tests/maasperf/
cp "$OUTPUT_DIR/results.json" "$OUTPUT_FILE"
