#!/bin/bash
#
# Helpers to run tests in CI.
#
# This runs both nose- and pytest-based tests, and fails if any of the
# processes fails.

set -o pipefail

MAAS_RAND_SEED="$(od -vAn -N8 -tx8 < /dev/urandom | tr -d ' ')"
PYTHONHASHSEED="$(shuf -i 0-4294967295 -n 1)"
export MAAS_RAND_SEED PYTHONHASHSEED

echo "MAAS_RAND_SEED=${MAAS_RAND_SEED}"
echo "PYTHONHASHSEED=${PYTHONHASHSEED}"

bin/test.parallel --emit-subunit | \
    bin/subunit-1to2 | \
    bin/subunit2junitxml --no-passthrough -f -o junit.xml | \
    bin/subunit2pyunit --no-passthrough
res1=$?
DBUPGRADE_ARGS='-v 0' bin/database --preserve run -- make syncdb
bin/database run -- bin/pytest -n auto --maxprocesses=6 --dist=loadscope --junit-xml=junit-pytest.xml
res2=$?
exit $((res1 + res2))
