#!/bin/bash -e
# Script to generated schemaspy output from the DB schema in the working
# tree.
#
# It installs the needed packages, makes sure the the bin db/ has the
# latest migrations, and then use bin/database run to run schemaspy on
# the local database.
DEPS_DIR=build/schemaspy/deps
OUT_DIR=build/schemaspy/out
SCHEMASPY_VERSION=6.2.4
SCHEMASPY_JAR=schemaspy-${SCHEMASPY_VERSION}.jar
PGJDBC_JAR=/usr/share/java/postgresql.jar
PORT=4444

sudo DEBIAN_FRONTEND=noninteractive apt install -y \
    default-jre-headless libpostgresql-jdbc-java

mkdir -p ${DEPS_DIR}
wget https://github.com/schemaspy/schemaspy/releases/download/v${SCHEMASPY_VERSION}/${SCHEMASPY_JAR} -O ${DEPS_DIR}/${SCHEMASPY_JAR}

make syncdb

cat <<EOF >${DEPS_DIR}/run
set -ex
socat -L./${DEPS_DIR}/.lock -v tcp-l:${PORT},bind=127.0.0.1,reuseaddr,fork unix:db/.s.PGSQL.5432 &
SOCAT_PID=\$!
while [ ! -f ${DEPS_DIR}/.lock ]; do 
    sleep 5; \
done
trap 'kill -15 \$SOCAT_PID' EXIT INT
java -jar ${DEPS_DIR}/${SCHEMASPY_JAR} \
    -t pgsql11 -dp ${PGJDBC_JAR} -host 127.0.0.1 -port ${PORT} \
    -vizjs -imageformat svg -nopages -hq \
    -o ${OUT_DIR} -u $USER -db maas
EOF

bin/database --preserve run -- bash ${DEPS_DIR}/run
