#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"/..

# This script checks to see if scss styles need to be rebuilt, based
# on whether any *.scss files appear in the output of `git status`.
# The --porcelain option is used to ensure that the output of 'git status' is
# expected to be formatted for use by scripts, and is consistent over time.

git status -z \
    | xargs -0 -n 1 echo | cut -c 4- \
    | egrep -q '\.scss$'

exit $?
