#!/bin/bash

ROOT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd)"
RUN_DIR=$ROOT_DIR=/.run

sudo add-apt-repository -u ppa:maas/next-proposed
sudo apt install authbind maas-dhcp chrony squid-deb-proxy
if grep -q "^BindsTo=maas" /lib/systemd/system/maas-dhcpd.service
then
    # Since we'll run the rackd service manuall, without using systemd,
    # maas-dhcp- can't depend on maas-rackd.
    echo "Unbinding maas-dhcp from maas-rackd"
    sudo sed -i "s/^BindsTo=maas/#BindsTo=maas/" \
        /lib/systemd/system/maas-dhcpd.service
    sudo systemctl daemon-reload
fi

echo "Changing ownership of /var/lib/maas"
sudo chown -R $USER /var/lib/maas 

echo "Done. Don't forget to ensure that sudo doesn't require a password."
