#!/bin/bash -e

exit_error() {
    echo "$@" >&2
    exit 1
}

msg() {
    echo "---" "$@"
}


sql_dump_file="$1"

if [ -z "$sql_dump_file" ]; then
    exit_error "SQL dump file not specified"
fi

if [ ! -r "$sql_dump_file" ]; then
    exit_error "SQL dump file not found"
fi

msg "importing SQL dump"
psql -c "\i $sql_dump_file" >/dev/null

msg "upgrading schema"
bin/maas-region dbupgrade

msg "dumping updated database file"
pg_dump "$PGDATABASE" --no-owner --no-privileges --format=plain --restrict-key=jDB4gdI1N8dbUCAC3vcdCvWs48TBU3tT39yhtb0ijqwqYnAc3QoCur8LfK1MnsD -f "$sql_dump_file"
