export type Page = { heading: string; headingLevel?: number; url: string };
export const pages: Page[] = [
  { heading: "Login", url: "/login" },
  { heading: "SSH keys for admin", url: "/intro/user" },
  { heading: "Devices", url: "/devices" },
  { heading: "Controllers", url: "/controllers" },
  { heading: "Networks", url: "/networks" },
  { heading: "Machines", url: "/machines" },
  { heading: "LXD", url: "/kvm/lxd" },
  { heading: "Images", url: "/images" },
  { heading: "DNS", url: "/domains" },
  { heading: "Availability zones", url: "/zones" },
  {
    heading: "Settings",
    headingLevel: 2,
    url: "/settings/configuration/general",
  },
  { heading: "My preferences", headingLevel: 2, url: "/account/prefs/details" },
];
export const routes: Record<string, string> = {
  controllers: "/controllers",
  devices: "/devices",
  domains: "/domains",
  home: "/",
  images: "/images",
  "images setup": "/intro/images",
  kvm: "/kvm",
  "maas setup": "/intro",
  "machines list": "/machines",
  networks: "/networks",
  "networks by fabric": "/networks?by=fabric",
  "network discovery": "/network-discovery",
  pools: "/pools",
  preferences: "/account/prefs",
  settings: "/settings",
  "settings general": "/settings/configuration/general",
  "settings commissioning": "/settings/configuration/commissioning",
  "settings deploy": "/settings/configuration/deploy",
  "settings kernel parameters": "/settings/configuration/kernel-parameters",
  "settings security protocols": "/settings/security/security-protocols",
  "settings secret storage": "/settings/security/secret-storage",
  "settings token expiration": "/settings/security/session-timeout",
  "settings ipmi settings": "/settings/security/ipmi-settings",
  "settings users": "/settings/user-management/users",
  "settings groups": "/settings/user-management/groups",
  "settings single sign-on": "/settings/user-management/single-sign-on",
  "settings ubuntu images": "/settings/images/ubuntu",
  "settings windows images": "/settings/images/windows",
  "settings vmware images": "/settings/images/vmware",
  "settings license keys": "/settings/license-keys",
  "settings storage": "/settings/storage",
  "settings proxy": "/settings/network/proxy",
  "settings dns": "/settings/network/dns",
  "settings ntp": "/settings/network/ntp",
  "settings syslog": "/settings/network/syslog",
  "settings network discovery": "/settings/network/network-discovery",
  "settings commissioning scripts": "/settings/scripts/commissioning",
  "settings deployment scripts": "/settings/scripts/deploying",
  "settings testing scripts": "/settings/scripts/testing",
  "settings dhcp snippets": "/settings/dhcp",
  "settings package repositories": "/settings/repositories",
  subnets: "/networks/subnets?by=fabric",
  "user setup": "/intro/user",
  zones: "/zones",
};
// longer timeout that can be useful for slow commands
export const LONG_TIMEOUT = 30000;
// extra-long timeout for operations that may take significantly
// longer due to backend workflows (e.g. first-time image sync)
export const VERY_LONG_TIMEOUT = 60000;
