# Generated by Django 2.2.12 on 2020-06-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("auth", "0004_user_email_allow_null")]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
