#!/usr/bin/env python3

import sys
import maascli

if sys.argv[0].split('/')[-1:] == "maas-cli":
    sys.stderr.write("""
  WARNING: The maas-cli command is deprecated and will be removed in a future
  version. From now on please use 'maas' instead.
""")

sys.exit(maascli.main())

