name: maas-power-driver-recs
version: '1.0.0'
summary: MAAS power driver for RECS
description: MAAS power driver for RECS BMCs
grade: devel
confinement: strict
base: core26

plugs:
  power-driver:
    interface: content
    content: power-driver

parts:
  recs-driver:
    plugin: python
    source: .
services:
  recs-driver:
    command: bin/recs-driver start
    plugs:
      - network
    sockets:
      recs:
        listen-stream: $SNAP_COMMON/power-driver/recs.sock
