name: maas-power-driver-recs
version: '1.0.0'
summary: MAAS power driver for RECS
description: MAAS power driver for RECS BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

plugs:
  power-driver:
    interface: content
    content: power-driver
    target: $SNAP_COMMON/power-driver

apps:
  status:
    command: bin/recs-driver status

parts:
  recs-driver:
    plugin: python
    source: .
    build-attributes:
      - enable-usrmerge
    override-build: |
      /usr/bin/python3 -m pip install --prefix=$CRAFT_PART_INSTALL/usr --no-build-isolation --root-user-action=ignore .
      find $CRAFT_PART_INSTALL -type f -executable -exec sed -i '1 s|^#!.*python3.*$|#!/usr/bin/env python3|' {} +

  tree:
    plugin: dump
    source: snap/local/tree
