name: maas-power-driver-redfish
version: "1.0.0"
summary: MAAS power driver for Redfish
description: MAAS power driver for Redfish BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

apps:
  redfish-driver:
    command: bin/redfish-driver start
    plugs:
      - network
      - power-drivers
    sockets:
      redfish:
        listen-stream: $SNAP_COMMON/power-drivers/redfish.sock

plugs:
  power-drivers:
    interface: content
    content: power-drivers
    target: $SNAP_COMMON/power-drivers

parts:
  redfish-driver:
    plugin: python
    source: .
