# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maascommon.enums.boot_resources import BootResourceFileType
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class BootResourceFileBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    extra: Union[dict, Unset] = Field(default=UNSET, required=False)
    filename: Union[str, Unset] = Field(default=UNSET, required=False)
    filename_on_disk: Union[str, Unset] = Field(default=UNSET, required=False)
    filetype: Union[BootResourceFileType, Unset] = Field(
        default=UNSET, required=False
    )
    largefile_id: Union[int, None, Unset] = Field(
        default=UNSET, required=False
    )
    resource_set_id: Union[int, None, Unset] = Field(
        default=UNSET, required=False
    )
    sha256: Union[str, Unset] = Field(default=UNSET, required=False)
    size: Union[int, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)
