# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from typing import Any

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class DatabaseConfigurationBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    name: str | Unset = Field(default=UNSET)
    value: Any | Unset = Field(default=UNSET)
