# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class DjangoSessionBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    expire_date: Union[datetime, Unset] = Field(default=UNSET, required=False)
    session_data: Union[str, Unset] = Field(default=UNSET, required=False)
    session_key: Union[str, Unset] = Field(default=UNSET, required=False)
