# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class FabricBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    class_type: str | None | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    description: str | None | Unset = Field(default=UNSET)
    name: str | None | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
