# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class FabricBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    class_type: Union[str, None, Unset] = Field(default=UNSET)
    created: Union[datetime, Unset] = Field(default=UNSET)
    description: Union[str, None, Unset] = Field(default=UNSET)
    name: Union[str, None, Unset] = Field(default=UNSET)
    updated: Union[datetime, Unset] = Field(default=UNSET)
