# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class FileStorageBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    content: Union[str, Unset] = Field(default=UNSET, required=False)
    filename: Union[str, Unset] = Field(default=UNSET, required=False)
    key: Union[str, Unset] = Field(default=UNSET, required=False)
    owner_id: Union[int, None, Unset] = Field(default=UNSET, required=False)
