# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.simplestreams.models import (
    SimpleStreamsBootloaderProductList,
    SimpleStreamsMultiFileProductList,
    SimpleStreamsSingleFileProductList,
)


class ImageManifestBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    boot_source_id: Union[int, Unset] = Field(default=UNSET, required=False)
    last_update: Union[datetime, Unset] = Field(default=UNSET, required=False)
    manifest: Union[
        list[
            Union[
                SimpleStreamsBootloaderProductList,
                SimpleStreamsSingleFileProductList,
                SimpleStreamsMultiFileProductList,
            ]
        ],
        Unset,
    ] = Field(default=UNSET, required=False)
