# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.simplestreams.models import (
    SimpleStreamsBootloaderProductList,
    SimpleStreamsMultiFileProductList,
    SimpleStreamsSingleFileProductList,
)


class ImageManifestBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    boot_source_id: int | Unset = Field(default=UNSET)
    last_update: datetime | Unset = Field(default=UNSET)
    manifest: (
        list[
            SimpleStreamsBootloaderProductList
            | SimpleStreamsSingleFileProductList
            | SimpleStreamsMultiFileProductList
        ]
        | Unset
    ) = Field(default=UNSET)
