# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maascommon.enums.interface import InterfaceType
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.models.interfaces import Link


class InterfaceBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET)
    enabled: Union[bool, Unset] = Field(default=UNSET)
    interface_speed: Union[int, Unset] = Field(default=UNSET)
    link_connected: Union[bool, Unset] = Field(default=UNSET)
    link_speed: Union[int, Unset] = Field(default=UNSET)
    links: Union[list[Link], Unset] = Field(default=UNSET)
    mac_address: Union[str, None, Unset] = Field(default=UNSET)
    name: Union[str, Unset] = Field(default=UNSET)
    node_config_id: Union[int, None, Unset] = Field(
        default=UNSET
    )
    sriov_max_vf: Union[int, Unset] = Field(default=UNSET)
    switch_id: Union[int, None, Unset] = Field(default=UNSET)
    type: Union[InterfaceType, Unset] = Field(default=UNSET)
    updated: Union[datetime, Unset] = Field(default=UNSET)
    vlan_id: Union[int, None, Unset] = Field(default=UNSET)
