# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maascommon.enums.interface import InterfaceType
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.models.interfaces import Link


class InterfaceBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: datetime | Unset = Field(default=UNSET)
    enabled: bool | Unset = Field(default=UNSET)
    interface_speed: int | Unset = Field(default=UNSET)
    link_connected: bool | Unset = Field(default=UNSET)
    link_speed: int | Unset = Field(default=UNSET)
    links: list[Link] | Unset = Field(default=UNSET)
    mac_address: str | None | Unset = Field(default=UNSET)
    name: str | Unset = Field(default=UNSET)
    node_config_id: int | None | Unset = Field(default=UNSET)
    sriov_max_vf: int | Unset = Field(default=UNSET)
    switch_id: int | None | Unset = Field(default=UNSET)
    type: InterfaceType | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    vlan_id: int | None | Unset = Field(default=UNSET)
