# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maascommon.enums.ipranges import IPRangeType
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class IPRangeBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    comment: str | None | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    end_ip: IPvAnyAddress | Unset = Field(default=UNSET)
    start_ip: IPvAnyAddress | Unset = Field(default=UNSET)
    subnet_id: int | Unset = Field(default=UNSET)
    type: IPRangeType | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    user_id: int | None | Unset = Field(default=UNSET)

    def must_trigger_workflow(self) -> bool:
        return (
            not isinstance(self.start_ip, Unset)
            or not isinstance(self.end_ip, Unset)
            or not isinstance(self.type, Unset)
            or not isinstance(self.subnet_id, Unset)
        )
