# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from typing import Union

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maascommon.enums.ipaddress import IpAddressFamily, LeaseAction
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class LeaseBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    action: Union[LeaseAction, Unset] = Field(default=UNSET, required=False)
    hostname: Union[str, Unset] = Field(default=UNSET, required=False)
    ip: Union[IPvAnyAddress, Unset] = Field(default=UNSET, required=False)
    ip_family: Union[IpAddressFamily, Unset] = Field(
        default=UNSET, required=False
    )
    lease_time_seconds: Union[int, Unset] = Field(
        default=UNSET, required=False
    )
    mac: Union[str, Unset] = Field(default=UNSET, required=False)
    timestamp_epoch: Union[int, Unset] = Field(default=UNSET, required=False)
