# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maascommon.enums.node import HardwareDeviceTypeEnum, NodeStatus
from maascommon.enums.power import PowerState
from maasservicelayer.enums.power_drivers import PowerTypeEnum
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class MachineBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    architecture: Union[str, None, Unset] = Field(
        default=UNSET, required=False
    )
    cpu_count: Union[int, Unset] = Field(default=UNSET, required=False)
    cpu_speed: Union[int, Unset] = Field(default=UNSET, required=False)
    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    current_commissioning_script_set_id: Union[int, None, Unset] = Field(
        default=UNSET, required=False
    )
    current_installation_script_set_id: Union[int, None, Unset] = Field(
        default=UNSET, required=False
    )
    current_testing_script_set_id: Union[int, None, Unset] = Field(
        default=UNSET, required=False
    )
    description: Union[str, Unset] = Field(default=UNSET, required=False)
    distro_series: Union[str, Unset] = Field(default=UNSET, required=False)
    error_description: Union[str, Unset] = Field(default=UNSET, required=False)
    fqdn: Union[str, Unset] = Field(default=UNSET, required=False)
    hostname: Union[str, Unset] = Field(default=UNSET, required=False)
    hwe_kernel: Union[str, None, Unset] = Field(default=UNSET, required=False)
    id: Union[int, Unset] = Field(default=UNSET, required=False)
    locked: Union[bool, Unset] = Field(default=UNSET, required=False)
    memory: Union[int, Unset] = Field(default=UNSET, required=False)
    osystem: Union[str, Unset] = Field(default=UNSET, required=False)
    owner: Union[str, None, Unset] = Field(default=UNSET, required=False)
    owner_id: Union[int, None, Unset] = Field(default=UNSET, required=False)
    power_state: Union[PowerState, Unset] = Field(
        default=UNSET, required=False
    )
    power_state_updated: Union[datetime, None, Unset] = Field(
        default=UNSET, required=False
    )
    power_type: Union[PowerTypeEnum, None, Unset] = Field(
        default=UNSET, required=False
    )
    status: Union[NodeStatus, Unset] = Field(default=UNSET, required=False)
    system_id: Union[str, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)


class PciDeviceBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    bus_number: Union[int, Unset] = Field(default=UNSET, required=False)
    commissioning_driver: Union[str, Unset] = Field(
        default=UNSET, required=False
    )
    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    device_number: Union[int, Unset] = Field(default=UNSET, required=False)
    hardware_type: Union[HardwareDeviceTypeEnum, Unset] = Field(
        default=UNSET, required=False
    )
    id: Union[int, Unset] = Field(default=UNSET, required=False)
    pci_address: Union[str, Unset] = Field(default=UNSET, required=False)
    product_id: Union[str, Unset] = Field(default=UNSET, required=False)
    product_name: Union[str, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)
    vendor_id: Union[str, Unset] = Field(default=UNSET, required=False)
    vendor_name: Union[str, Unset] = Field(default=UNSET, required=False)


class UsbDeviceBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    bus_number: Union[int, Unset] = Field(default=UNSET, required=False)
    commissioning_driver: Union[str, Unset] = Field(
        default=UNSET, required=False
    )
    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    device_number: Union[int, Unset] = Field(default=UNSET, required=False)
    hardware_type: Union[HardwareDeviceTypeEnum, Unset] = Field(
        default=UNSET, required=False
    )
    id: Union[int, Unset] = Field(default=UNSET, required=False)
    product_id: Union[str, Unset] = Field(default=UNSET, required=False)
    product_name: Union[str, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)
    vendor_id: Union[str, Unset] = Field(default=UNSET, required=False)
    vendor_name: Union[str, Unset] = Field(default=UNSET, required=False)
