# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.models.fields import MacAddress


class NeighbourBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    count: int | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    interface_id: int | Unset = Field(default=UNSET)
    ip: IPvAnyAddress | None | Unset = Field(default=UNSET)
    mac_address: MacAddress | None | Unset = Field(default=UNSET)
    time: int | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    vid: int | None | Unset = Field(default=UNSET)
