# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class NodeUserDataBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    data: bytes | Unset = Field(default=UNSET)
    for_ephemeral_environment: bool | Unset = Field(default=UNSET)
    node_id: int | Unset = Field(default=UNSET)
