# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maascommon.enums.node import NodeStatus, NodeTypeEnum
from maascommon.enums.power import PowerState
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class NodeBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    boot_interface_id: int | None | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    current_commissioning_script_set_id: int | None | Unset = Field(
        default=UNSET
    )
    current_config_id: int | None | Unset = Field(default=UNSET)
    current_installation_script_set_id: int | None | Unset = Field(
        default=UNSET
    )
    current_testing_script_set_id: int | None | Unset = Field(default=UNSET)
    domain_id: int | None | Unset = Field(default=UNSET)
    error_description: str | Unset = Field(default=UNSET)
    hostname: str | Unset = Field(default=UNSET)
    node_type: NodeTypeEnum | Unset = Field(default=UNSET)
    owner_id: int | None | Unset = Field(default=UNSET)
    power_state: PowerState | Unset = Field(default=UNSET)
    power_state_updated: datetime | None | Unset = Field(default=UNSET)
    status: NodeStatus | Unset = Field(default=UNSET)
    system_id: str | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
