# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class NodeGroupToRackControllerBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    id: Union[int, Unset] = Field(default=UNSET, required=False)
    subnet_id: Union[int, Unset] = Field(default=UNSET, required=False)
    uuid: Union[str, Unset] = Field(default=UNSET, required=False)
