# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from typing import Union

from pydantic import Field

from maascommon.openfga.base import (
    MAASResourceEntitlement,
    OpenFGAEntitlementResourceType,
    PoolResourceEntitlements,
)
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class OpenFGATupleBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    object_id: Union[str, Unset] = Field(default=UNSET, required=False)
    object_type: Union[str, Unset] = Field(default=UNSET, required=False)
    relation: Union[str, Unset] = Field(default=UNSET, required=False)
    user: Union[str, Unset] = Field(default=UNSET, required=False)
    user_type: Union[str, Unset] = Field(default=UNSET, required=False)

    @classmethod
    def build_user_member_group(
        cls, user_id: int, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"user:{user_id}",
            user_type="user",
            relation="member",
            object_id=str(group_id),
            object_type="group",
        )

    @classmethod
    def build_group_can_edit_machines_in_pool(
        cls, group_id: int, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=PoolResourceEntitlements.CAN_EDIT_MACHINES,
            object_id=pool_id,
            object_type=OpenFGAEntitlementResourceType.POOL,
        )

    @classmethod
    def build_group_can_view_machines_in_pool(
        cls, group_id: int, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=PoolResourceEntitlements.CAN_VIEW_MACHINES,
            object_id=pool_id,
            object_type=OpenFGAEntitlementResourceType.POOL,
        )

    @classmethod
    def build_group_can_view_available_machines_in_pool(
        cls, group_id: int, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=PoolResourceEntitlements.CAN_VIEW_AVAILABLE_MACHINES,
            object_id=pool_id,
            object_type=OpenFGAEntitlementResourceType.POOL,
        )

    @classmethod
    def build_group_can_deploy_machines_in_pool(
        cls, group_id: int, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=PoolResourceEntitlements.CAN_DEPLOY_MACHINES,
            object_id=pool_id,
            object_type=OpenFGAEntitlementResourceType.POOL,
        )

    @classmethod
    def build_group_can_edit_machines(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_MACHINES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_machines(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_MACHINES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_available_machines(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_AVAILABLE_MACHINES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_deploy_machines(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_DEPLOY_MACHINES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_global_entities(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_GLOBAL_ENTITIES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_global_entities(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_GLOBAL_ENTITIES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_controllers(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_CONTROLLERS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_controllers(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_CONTROLLERS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_identities(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_IDENTITIES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_identities(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_IDENTITIES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_boot_entities(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_BOOT_ENTITIES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_boot_entities(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_BOOT_ENTITIES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_configurations(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_CONFIGURATIONS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_configurations(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_CONFIGURATIONS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_notifications(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_NOTIFICATIONS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_notifications(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_NOTIFICATIONS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_edit_license_keys(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_EDIT_LICENSE_KEYS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_license_keys(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_LICENCE_KEYS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_devices(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_DEVICES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_ipaddresses(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_IPADDRESSES,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_group_can_view_dnsrecords(
        cls, group_id: int
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation=MAASResourceEntitlement.CAN_VIEW_DNSRECORDS,
            object_id="0",
            object_type=OpenFGAEntitlementResourceType.MAAS,
        )

    @classmethod
    def build_pool(cls, pool_id: str) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user="maas:0",
            user_type="user",
            relation="parent",
            object_id=pool_id,
            object_type=OpenFGAEntitlementResourceType.POOL,
        )
