# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maascommon.enums.package_repositories import (
    ComponentsToDisableEnum,
    KnownArchesEnum,
    KnownComponentsEnum,
    PocketsToDisableEnum,
)
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.models.fields import PackageRepoUrl


class PackageRepositoryBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    arches: Union[set[KnownArchesEnum], Unset] = Field(
        default=UNSET
    )
    components: Union[set[KnownComponentsEnum], Unset] = Field(
        default=UNSET
    )
    created: Union[datetime, Unset] = Field(default=UNSET)
    default: Union[bool, Unset] = Field(default=UNSET)
    disable_sources: Union[bool, Unset] = Field(default=UNSET)
    disabled_components: Union[set[ComponentsToDisableEnum], Unset] = Field(
        default=UNSET
    )
    disabled_pockets: Union[set[PocketsToDisableEnum], Unset] = Field(
        default=UNSET
    )
    distributions: Union[list[str], Unset] = Field(
        default=UNSET
    )
    enabled: Union[bool, Unset] = Field(default=UNSET)
    key: Union[str, Unset] = Field(default=UNSET)
    name: Union[str, Unset] = Field(default=UNSET)
    updated: Union[datetime, Unset] = Field(default=UNSET)
    url: Union[PackageRepoUrl, Unset] = Field(default=UNSET)
