# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maascommon.enums.package_repositories import (
    ComponentsToDisableEnum,
    KnownArchesEnum,
    KnownComponentsEnum,
    PocketsToDisableEnum,
)
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset
from maasservicelayer.models.fields import PackageRepoUrl


class PackageRepositoryBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    arches: set[KnownArchesEnum] | Unset = Field(default=UNSET)
    components: set[KnownComponentsEnum] | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    default: bool | Unset = Field(default=UNSET)
    disable_sources: bool | Unset = Field(default=UNSET)
    disabled_components: set[ComponentsToDisableEnum] | Unset = Field(
        default=UNSET
    )
    disabled_pockets: set[PocketsToDisableEnum] | Unset = Field(default=UNSET)
    distributions: list[str] | Unset = Field(default=UNSET)
    enabled: bool | Unset = Field(default=UNSET)
    key: str | Unset = Field(default=UNSET)
    name: str | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    url: PackageRepoUrl | Unset = Field(default=UNSET)
