# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class ResourcePoolBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET)
    description: Union[str, Unset] = Field(default=UNSET)
    name: Union[str, Unset] = Field(default=UNSET)
    updated: Union[datetime, Unset] = Field(default=UNSET)


class ResourcePoolWithSummaryBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET)
    description: Union[str, Unset] = Field(default=UNSET)
    machine_ready_count: Union[int, Unset] = Field(
        default=UNSET
    )
    machine_total_count: Union[int, Unset] = Field(
        default=UNSET
    )
    name: Union[str, Unset] = Field(default=UNSET)
    updated: Union[datetime, Unset] = Field(default=UNSET)
