# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maascommon.enums.scriptresult import ScriptStatus
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class ScriptResultBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    id: Union[int, Unset] = Field(default=UNSET, required=False)
    output: Union[str, Unset] = Field(default=UNSET, required=False)
    parameters: Union[str, Unset] = Field(default=UNSET, required=False)
    result: Union[str, Unset] = Field(default=UNSET, required=False)
    script_set_id: Union[int, Unset] = Field(default=UNSET, required=False)
    status: Union[ScriptStatus, Unset] = Field(default=UNSET, required=False)
    stderr: Union[str, Unset] = Field(default=UNSET, required=False)
    stdout: Union[str, Unset] = Field(default=UNSET, required=False)
    suppressed: Union[bool, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)
