# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maascommon.enums.scriptresult import ScriptStatus
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class ScriptResultBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: datetime | Unset = Field(default=UNSET)
    output: str | Unset = Field(default=UNSET)
    parameters: dict | Unset = Field(default=UNSET)
    result: str | Unset = Field(default=UNSET)
    script_set_id: int | Unset = Field(default=UNSET)
    status: ScriptStatus | Unset = Field(default=UNSET)
    stderr: str | Unset = Field(default=UNSET)
    stdout: str | Unset = Field(default=UNSET)
    suppressed: bool | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
