# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class TrustedSshHostKeyBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: datetime | Unset = Field(default=UNSET)
    host: str | Unset = Field(default=UNSET)
    key_type: str | Unset = Field(default=UNSET)
    label: str | None | Unset = Field(default=UNSET)
    public_key: str | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
