# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maascommon.enums.sshkeys import SshKeysProtocolType
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class SshKeyBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    auth_id: str | None | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    key: str | Unset = Field(default=UNSET)
    protocol: SshKeysProtocolType | None | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    user_id: int | Unset = Field(default=UNSET)
