# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maascommon.enums.ipaddress import IpAddressType
from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class StaticIPAddressBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    alloc_type: IpAddressType | Unset = Field(default=UNSET)
    created: datetime | Unset = Field(default=UNSET)
    ip: IPvAnyAddress | None | Unset = Field(default=UNSET)
    lease_time: int | Unset = Field(default=UNSET)
    subnet_id: int | None | Unset = Field(default=UNSET)
    temp_expires_on: datetime | None | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    user_id: int | None | Unset = Field(default=UNSET)

    def must_trigger_workflow(self) -> bool:
        return (
            not isinstance(self.ip, Unset)
            or not isinstance(self.alloc_type, Unset)
            or not isinstance(self.subnet_id, Unset)
        )
