# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class StaticRouteBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: datetime | Unset = Field(default=UNSET)
    destination_id: int | Unset = Field(default=UNSET)
    gateway_ip: IPvAnyAddress | Unset = Field(default=UNSET)
    metric: int | Unset = Field(default=UNSET)
    source_id: int | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
