# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class SwitchBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    description: Union[str, None, Unset] = Field(default=UNSET, required=False)
    ip_address: Union[str, IPvAnyAddress, None, Unset] = Field(
        default=UNSET, required=False
    )
    mac_address: Union[str, Unset] = Field(default=UNSET, required=False)
    manufacturer: Union[str, None, Unset] = Field(
        default=UNSET, required=False
    )
    model: Union[str, None, Unset] = Field(default=UNSET, required=False)
    name: Union[str, None, Unset] = Field(default=UNSET, required=False)
    subnet_id: Union[int, None, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)
    vlan_id: Union[int, None, Unset] = Field(default=UNSET, required=False)
