# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class OIDCRevokedTokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    provider_id: Union[int, Unset] = Field(default=UNSET, required=False)
    revoked_at: Union[datetime, Unset] = Field(default=UNSET, required=False)
    token_hash: Union[str, Unset] = Field(default=UNSET, required=False)
    user_email: Union[str, Unset] = Field(default=UNSET, required=False)


class TokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    callback: Union[str, None, Unset] = Field(default=UNSET, required=False)
    callback_confirmed: Union[bool, Unset] = Field(
        default=UNSET, required=False
    )
    consumer_id: Union[int, Unset] = Field(default=UNSET, required=False)
    is_approved: Union[bool, Unset] = Field(default=UNSET, required=False)
    key: Union[str, Unset] = Field(default=UNSET, required=False)
    secret: Union[str, Unset] = Field(default=UNSET, required=False)
    timestamp: Union[int, Unset] = Field(default=UNSET, required=False)
    token_type: Union[int, Unset] = Field(default=UNSET, required=False)
    user_id: Union[int, None, Unset] = Field(default=UNSET, required=False)
    verifier: Union[str, Unset] = Field(default=UNSET, required=False)
