# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class OIDCRevokedTokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    provider_id: Union[int, Unset] = Field(default=UNSET)
    revoked_at: Union[datetime, Unset] = Field(default=UNSET)
    token_hash: Union[str, Unset] = Field(default=UNSET)
    user_email: Union[str, Unset] = Field(default=UNSET)


class RefreshTokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET)
    expires_at: Union[datetime, Unset] = Field(default=UNSET)
    token: Union[str, Unset] = Field(default=UNSET)
    updated: Union[datetime, Unset] = Field(default=UNSET)
    user_id: Union[int, Unset] = Field(default=UNSET)


class TokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    callback: Union[str, None, Unset] = Field(default=UNSET)
    callback_confirmed: Union[bool, Unset] = Field(
        default=UNSET
    )
    consumer_id: Union[int, Unset] = Field(default=UNSET)
    is_approved: Union[bool, Unset] = Field(default=UNSET)
    key: Union[str, Unset] = Field(default=UNSET)
    secret: Union[str, Unset] = Field(default=UNSET)
    timestamp: Union[int, Unset] = Field(default=UNSET)
    token_type: Union[int, Unset] = Field(default=UNSET)
    user_id: Union[int, None, Unset] = Field(default=UNSET)
    verifier: Union[str, Unset] = Field(default=UNSET)
