# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class OIDCRevokedTokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    provider_id: int | Unset = Field(default=UNSET)
    revoked_at: datetime | Unset = Field(default=UNSET)
    token_hash: str | Unset = Field(default=UNSET)
    user_email: str | Unset = Field(default=UNSET)


class RefreshTokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: datetime | Unset = Field(default=UNSET)
    expires_at: datetime | Unset = Field(default=UNSET)
    token: str | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    user_id: int | Unset = Field(default=UNSET)


class TokenBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    callback: str | None | Unset = Field(default=UNSET)
    callback_confirmed: bool | Unset = Field(default=UNSET)
    consumer_id: int | Unset = Field(default=UNSET)
    is_approved: bool | Unset = Field(default=UNSET)
    key: str | Unset = Field(default=UNSET)
    secret: str | Unset = Field(default=UNSET)
    timestamp: int | Unset = Field(default=UNSET)
    token_type: int | Unset = Field(default=UNSET)
    user_id: int | None | Unset = Field(default=UNSET)
    verifier: str | Unset = Field(default=UNSET)
