# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime

from pydantic import Field
from pydantic.networks import IPvAnyAddress

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class VlanBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: datetime | Unset = Field(default=UNSET)
    description: str | Unset = Field(default=UNSET)
    dhcp_on: bool | Unset = Field(default=UNSET)
    external_dhcp: IPvAnyAddress | None | Unset = Field(default=UNSET)
    fabric_id: int | Unset = Field(default=UNSET)
    mtu: int | Unset = Field(default=UNSET)
    name: str | None | Unset = Field(default=UNSET)
    primary_rack_id: int | None | Unset = Field(default=UNSET)
    relay_vlan_id: int | None | Unset = Field(default=UNSET)
    relayed_vlan_id: int | None | Unset = Field(default=UNSET)
    secondary_rack_id: int | None | Unset = Field(default=UNSET)
    space_id: int | None | Unset = Field(default=UNSET)
    updated: datetime | Unset = Field(default=UNSET)
    vid: int | Unset = Field(default=UNSET)
