# Copyright 2015-2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Signals coming off models."""

__all__ = [
    "blockdevices",
    "bmc",
    "bootsources",
    "controllerinfo",
    "dhcpsnippet",
    "dnsdata",
    "dnsresource",
    "domain",
    "events",
    "interfaces",
    "iprange",
    "nodes",
    "regionrackrpcconnection",
    "resourcepool",
    "partitions",
    "podhints",
    "power",
    "scriptresult",
    "services",
    "staticipaddress",
    "subnet",
    "users",
    "vlan",
]

from maasserver.models.signals import (
    blockdevices,
    bmc,
    bootsources,
    controllerinfo,
    dhcpsnippet,
    dnsdata,
    dnsresource,
    domain,
    events,
    interfaces,
    iprange,
    nodes,
    partitions,
    podhints,
    power,
    regionrackrpcconnection,
    resourcepool,
    scriptresult,
    services,
    staticipaddress,
    subnet,
    users,
    vlan,
)
