# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 01:20
from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('maasserver', '0147_pod_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmc',
            name='tags',
            field=models.ManyToManyField(to='maasserver.Tag'),
        ),
    ]
