#!/bin/bash -e
#
# 50-maas-01-commissioning - Gather all commissioning data
#
# Copyright (C) 2012-2020 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# --- Start MAAS 1.0 script metadata ---
# name: 50-maas-01-commissioning
# title: Gather all commissioning data
# description: Gather all commissioning data
# script_type: commissioning
# timeout: 60
# --- End MAAS 1.0 script metadata ---

resources_bin="$DOWNLOAD_PATH/machine-resources"
arch="$(dpkg --print-architecture)"
wget "$MAAS_BASE_URL/machine-resources/$arch" -O "$resources_bin" >&2
chmod +x "$resources_bin"
"$resources_bin"
