debian/extras/99-maas-common-sudoers etc/sudoers.d
debian/tmp/usr/lib/maas/maas-delete-file
debian/tmp/usr/lib/maas/maas-write-file

# Install network monitoring scripts
debian/tmp/usr/lib/maas/network-monitor
debian/tmp/usr/lib/maas/beacon-monitor
debian/tmp/usr/lib/maas/dhcp-monitor

# Install unverified-ssh
# This is used for KVM host communication:
# https://bugs.launchpad.net/maas/+bug/1807231
debian/tmp/usr/lib/maas/unverified-ssh

usr/bin/maas-common /usr/lib/maas
