#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    purge)
        # Deleting user/group
        if getent passwd maas >/dev/null; then
            deluser maas || true
            delgroup maas || true
        fi
        rm -f /var/log/maas/maas.log
        rm -rf /var/lib/maas/gnupg
        rm -f /var/lib/maas/secret
        rm -f /var/lib/maas/maas_id
        rm -rf /var/log/maas/rsyslog
        rm -f /var/log/maas/rsyslog.conf

esac

rm -f /etc/rsyslog.d/99-maas.conf
