#!/bin/sh

set -e

. /usr/share/debconf/confmodule

#DEBHELPER#

deb-systemd-invoke stop 'maas-regiond.service' >/dev/null || true
deb-systemd-invoke stop 'maas-apiserver.service' >/dev/null || true
deb-systemd-invoke stop 'maas-temporal.service' >/dev/null || true
deb-systemd-invoke stop 'maas-temporal-worker.service' >/dev/null || true

. /usr/share/dbconfig-common/dpkg/prerm.pgsql
dbc_go maas-region-controller $@
