#!/usr/bin/dh-exec --with=install

debian/extras/99-maas-common-sudoers etc/sudoers.d
debian/tmp/usr/lib/maas/maas-delete-file
debian/tmp/usr/lib/maas/maas-write-file

# Install network monitoring scripts
debian/tmp/usr/lib/maas/network-monitor
debian/tmp/usr/lib/maas/beacon-monitor
debian/tmp/usr/lib/maas/dhcp-monitor

# Install an alias to maas-rack as maas-common.
# For information on the usage of '=>' here, see:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=245554
debian/extras/maas-rack => /usr/lib/maas/maas-common
