# Install static files
debian/tmp/usr/share/maas/web/static

# Install Apache Config
package-files/usr/share/maas/maas-http.conf usr/share/maas/

# Install new preseed files
package-files/etc/maas/preseeds /etc/maas

# Install driver configuration file
package-files/etc/maas/drivers.yaml etc/maas

# Install all other stuff
usr/bin/maas-region usr/sbin
usr/bin/maas-sampledata usr/bin
usr/bin/regiond usr/sbin
debian/extras/maas_remote_syslog_compress etc/cron.d
