#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -rf /var/cache/maas-proxy
    rm -rf /var/log/maas/proxy
    rm -rf /var/spool/maas-proxy
    rm -rf /var/lib/maas/maas-proxy.conf
fi

# MAAS installation disables system squid so it doesn't
# prevent MAAS from running our own squid daemon. As such,
# on removal, reenable squid.
deb-systemd-helper enable squid >/dev/null || true
deb-systemd-invoke start squid >/dev/null || true

#DEBHELPER#
