debian/extras/99-maas-common-sudoers etc/sudoers.d
debian/tmp/usr/lib/maas/maas-delete-file
debian/tmp/usr/lib/maas/maas-write-file

# Install network monitoring scripts
debian/tmp/usr/lib/maas/network-monitor
debian/tmp/usr/lib/maas/beacon-monitor
debian/tmp/usr/lib/maas/dhcp-monitor

# Install unverified-ssh
# This is used for KVM host communication:
# https://bugs.launchpad.net/maas/+bug/1807231
debian/tmp/usr/lib/maas/unverified-ssh

# Install commissioning binaries
debian/tmp/usr/share/maas/machine-resources/amd64 usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/arm64 usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/armhf usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/i386 usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/ppc64el usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/s390x usr/share/maas/machine-resources
debian/tmp/usr/share/maas/hardware-sync/amd64 usr/share/maas/hardware-sync
debian/tmp/usr/share/maas/hardware-sync/arm64 usr/share/maas/hardware-sync
debian/tmp/usr/share/maas/hardware-sync/armhf usr/share/maas/hardware-sync
debian/tmp/usr/share/maas/hardware-sync/i386 usr/share/maas/hardware-sync
debian/tmp/usr/share/maas/hardware-sync/ppc64el usr/share/maas/hardware-sync
debian/tmp/usr/share/maas/hardware-sync/s390x usr/share/maas/hardware-sync

usr/bin/maas-common /usr/lib/maas
etc/maas/certificates
