#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
    # Stop the system squid instance; MAAS runs its own.
    # Only the current squid.service is supported.
    deb-systemd-invoke stop 'squid.service' >/dev/null 2>&1 || true
    deb-systemd-helper disable 'squid.service' >/dev/null 2>&1 || true

    # Ensure log folder is created.
    install -d -o proxy -g proxy /var/log/maas/proxy

fi

#DEBHELPER#
