debian/tmp/usr/lib/python3*/dist-packages/provisioningserver

# Install commissioning binaries
debian/tmp/usr/share/maas/machine-resources/386 usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/amd64 usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/arm usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/arm64 usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/ppc64le usr/share/maas/machine-resources
debian/tmp/usr/share/maas/machine-resources/s390x usr/share/maas/machine-resources
