#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

# Move to the project root.
cd "$(dirname "$0")/../.."

# Start logging, if requested. Not using multilog here right now
# because there are race issues when restarting.
[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"

export PYTHONPATH=etc/:src/
export CELERY_CONFIG_MODULE=democeleryconfig_cluster

# Obtain the development settings for MAAS_URL and CLUSTER_UUID.
. etc/demo_maas_cluster.conf
export CLUSTER_UUID

script="$(readlink -f bin/maas-provision)"
exec $(command -v authbind && echo --deep) \
    pgrphack "${script}" start-cluster-controller \
    "${MAAS_URL}" -u "$(id -un)" -g "$(id -gn)"
