name: maas-power-driver-amt
version: '1.0.0'
summary: MAAS power driver for Intel AMT
description: MAAS power driver for Intel AMT BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

plugs:
  power-driver:
    interface: content
    content: power-driver
    target: $SNAP_COMMON/power-driver

parts:
  amt-driver:
    plugin: python
    source: .
    stage-packages:
      - amtterm
      - wsmancli

  tree:
    plugin: dump
    source: snap/local/tree
