name: Accessibility
on:
  push:
    branches:
      - main
      - "3.*"
jobs:
  cypress-axe:
    name: cypress-axe
    runs-on: ubuntu-24.04
    env:
      MAAS_URL: http://localhost:5240
    steps:
      - uses: actions/checkout@main
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Install snapd and core snaps
        run: |
          sudo snap install snapd
          sudo snap install core26 --candidate
      - name: Setup MAAS
        uses: canonical/setup-maas@main
        with:
          maas-url: ${{env.MAAS_URL}}/MAAS
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install Cypress
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          install-command: yarn install
      - name: Create MAAS admin
        run: sudo maas createadmin --username=admin --password=test --email=fake@example.org
      - name: Run cypress-axe accessibility tests
        uses: cypress-io/github-action@v4
        with:
          config: baseUrl=${{env.MAAS_URL}},pageLoadTimeout=100000
          install: false
          spec: "cypress/e2e/accessibility/**/*.spec.ts"
          wait-on: "${{env.MAAS_URL}}/MAAS/r/machines"
