name: maas-power-driver-apc
version: '1.0.0'
summary: MAAS power driver for APC
description: MAAS power driver for APC BMCs
grade: devel
confinement: strict
base: core26

plugs:
  power-driver:
    interface: content
    content: power-driver

parts:
  apc-driver:
    plugin: python
    source: .
    stage-packages:
      - snmp
services:
  apc-driver:
    command: bin/apc-driver start
    plugs:
      - network
    sockets:
      apc:
        listen-stream: $SNAP_COMMON/power-driver/apc.sock
