# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-30 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("piston3", "0002_auto_20151209_1652")]

    operations = [
        migrations.AlterUniqueTogether(
            name="nonce",
            unique_together=set([("token_key", "consumer_key", "key")]),
        )
    ]
