# Generated by Django 1.11.11 on 2019-08-30 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("piston3", "0002_auto_20151209_1652")]

    operations = [
        migrations.AlterUniqueTogether(
            name="nonce",
            unique_together={("token_key", "consumer_key", "key")},
        )
    ]
