#!/usr/bin/env bash
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Compatibility stub.  This script has been replaced by maas-import-pxe-files
# and if run, will simply call the newer script instead.
#
# Expect this script to disappear at some point.  Run maas-import-pxe-files
# instead.

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Treat unset variables as an error when substituting.
set -o nounset

cat >&2 <<EOF

Warning: maas-import-isos is obsolete, and will disappear in the future.
It has been replaced with maas-import-pxe-files.

Running maas-import-pxe-files now...

EOF

maas-import-pxe-files
