#!/usr/bin/env python2.7
# Copyright 2014 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Convert a "UEC" root image file to a root tarball.

This requires root privileges, because it needs to loop-mount the image file
in order to read its contents.
"""

from provisioningserver.import_images import uec2roottar


if __name__ == "__main__":
    parser = uec2roottar.make_argparser(__doc__)
    args = parser.parse_args()
    uec2roottar.main(args)
