#!/bin/sh -euf
# Copyright 2019 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Utility script to call ssh with options to disable strict host
# key checking.  Among other things, this is currently used for KVM
# host communication.

exec ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$@"
