name: maas-power-driver-dli
version: '1.0.0'
summary: MAAS power driver for DLI
description: MAAS power driver for DLI BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

plugs:
  power-driver:
    interface: content
    content: power-driver
    target: $SNAP_COMMON/power-driver

parts:
  dli-driver:
    plugin: python
    source: .
    stage-packages:
      - wget

  tree:
    plugin: dump
    source: snap/local/tree
