name: maas
adopt-info: maas
summary: Metal as a Service
description: |
  Total automation of your physical servers for amazing data center operational efficiency.
grade: stable
confinement: strict
base: core22
assumes:
  - snapd2.53
system-usernames:
  snap_daemon: shared
# epochs:
# 0: (2.5) PostgreSQL 9.5
# 1: (2.6) PostgreSQL 10
# 2: (2.8) move MAAS data to $SNAP_COMMON
# 3: (2.9) drop "all" mode and builtin PostgresSQL server
# 4: (3.5) supervisord -> Pebble migration
epoch: 4*

package-repositories:
  - type: apt
    ppa: maas/3.5-next

environment:
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/dist-packages
  LD_PRELOAD: $SNAP/usr/lib/snap-preload.so
  PEBBLE: $SNAP_COMMON/pebble

plugs:
  test-db-socket:
    interface: content
    content: db-socket
    target: $SNAP_COMMON/test-db-socket

slots:
  maas-logs:
    interface: content
    read:
      - $SNAP_COMMON/log

apps:
  pebble:
    daemon: simple
    command: bin/run-pebble-daemon
    plugs:
      - avahi-observe
      - hardware-observe
      - kernel-module-observe
      - mount-observe
      - network
      - network-bind
      - network-control
      - network-observe
      - snap-refresh-control
      - system-observe
      - time-control

  maas:
    command: bin/maas
    plugs:
      - home
      - mount-observe  # to read /proc/*/mounts
      - network # for external authentication
      - network-observe # to get default URL

  power:
    command: bin/maas-power
    plugs:
      - network

parts:
  pebble:
    plugin: go
    build-packages:
      - golang-go
    source-type: git
    source: https://github.com/canonical/pebble
    source-tag: v1.10.2

  maas:
    plugin: python
    source: .
    build-packages:
      - build-essential
      - git
      - libffi-dev
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - python3-setuptools
    stage-packages:
      - amtterm # AMT
      - avahi-utils
      - bind9
      - bind9-dnsutils
      - chrony
      - dns-root-data # for bind9
      - freeipmi-tools # IPMI
      - gpgv
      - ipmitool # Moonshot
      - iproute2
      - isc-dhcp-client
      - isc-dhcp-server
      - libatm1
      - libpq5
      - libsoap-lite-perl # Dependencies for AMT
      - libvirt-clients # Virsh
      - libxml-parser-lite-perl # Dependencies for AMT
      - libxml-parser-perl # Dependencies for AMT
      - libxtables12
      - lshw
      - nginx-core
      - nmap
      - openssh-client
      - python3-aiodns
      - python3-aiofiles
      - python3-aiohttp
      - python3-asyncpg
      - python3-attr
      - python3-babel
      - python3-bson
      - python3-certifi # for macaroonbakery
      - python3-cffi # for macaroonbakery
      - python3-cffi-backend # for macaroonbakery
      - python3-chardet
      - python3-crochet
      - python3-cryptography
      - python3-curtin
      - python3-dateutil
      - python3-distro-info
      - python3-django
      - python3-django-piston3
      - python3-fastapi
      - python3-formencode
      - python3-httplib2
      - python3-hvac
      - python3-idna # for macaroonbakery
      - python3-jsonschema
      - python3-lxml
      - python3-macaroonbakery
      - python3-markupsafe
      - python3-mimeparse
      - python3-nacl # for macaroonbakery
      - python3-netaddr
      - python3-netifaces
      - python3-oauthlib
      - python3-paramiko
      - python3-petname
      - python3-pexpect
      - python3-pkg-resources
      - python3-prometheus-client
      - python3-protobuf # for macaroonbakery
      - python3-psycopg2
      - python3-pylxd
      - python3-pymacaroons # for macaroonbakery
      - python3-pyparsing
      - python3-pypureomapi
      - python3-pyrsistent # for jsonschema
      - python3-pyvmomi
      - python3-requests
      - python3-requests-toolbelt  # for pylxd
      - python3-requests-unixsocket
      - python3-rfc3339 # for macaroonbakery
      - python3-seamicroclient
      - python3-simplestreams
      - python3-sqlalchemy
      - python3-starlette
      - python3-tempita
      - python3-temporalio
      - python3-twisted
      - python3-txtftp
      - python3-tz
      - python3-urllib3 # for macaroonbakery
      - python3-uvicorn
      - python3-yaml
      - python3-zhmcclient
      - python3-zope.interface
      - rsyslog
      - snmp # APC
      - squid
      - tcpdump
      - temporal
      - ubuntu-keyring
      - util-linux
      - wget # DLI
      - wsmancli # AMT
    organize:
      lib/python3.*/site-packages/etc/*: etc/
      lib/python3.*/site-packages/usr/bin/*: usr/bin/
      lib/python3.*/site-packages/usr/lib/*: usr/lib/
      lib/python3.*/site-packages/usr/sbin/*: usr/sbin/
      lib/python3.*/site-packages/usr/share/*: usr/share/
      usr/lib/curtin/helpers: usr/lib/python3/dist-packages/helpers/
      usr/lib/*-linux-gnu/blas/*: usr/lib/
    stage:
      - bin
      - -bin/activate*
      - -bin/Activate*
      - -bin/maas-sampledata
      - etc/bind
      - etc/chrony
      - etc/freeipmi
      - etc/libvirt
      - etc/maas
      - etc/nginx
      - etc/openwsman
      - sbin
      - lib
      - -lib/python3.*/site-packages/etc
      - -lib/python3.*/site-packages/usr
      - -lib/python3/dist-packages/maastesting
      - pyvenv.cfg
      - usr/bin
      - -usr/bin/xdg-*
      - usr/lib
      - usr/sbin
      - usr/share/dns
      - usr/share/ieee-data
      - usr/share/keyrings
      - usr/share/maas
      - usr/share/nginx
      - usr/share/perl
      - usr/share/perl5
      - usr/share/squid*
      - var/lib/ieee-data
      - var/lib/temporal
    override-build: |
      # Do not `craftctl default`: the python plugin would create an isolated venv and would need to install setuptools from pip.
      python3 -m venv --system-site-packages $CRAFT_PART_INSTALL
      VENV_PYTHON=$CRAFT_PART_INSTALL/bin/python3
      $VENV_PYTHON -m pip install --no-build-isolation .
      find $CRAFT_PART_INSTALL -type f -executable -exec sed -i '1 s|^#\!.*python3.*$|#!/usr/bin/env python3|' {} +

      cp -a package-files/* $CRAFT_PART_INSTALL
      # If python3-netaddr contains absolute symlinks.
      # See https://bugs.launchpad.net/snapcraft/+bug/1774410
      ln -sf ../../../../../../var/lib/ieee-data/oui.txt $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/oui.txt
      ln -sf ../../../../../../var/lib/ieee-data/iab.txt $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/iab.txt
    override-prime: |
      (cd $CRAFT_PART_SRC; craftctl set version="$(utilities/package-version)")
      craftctl default
      python3 -m compileall -j 0 -q .

  ui:
    plugin: make
    source: .
    build-packages:
      - curl
    override-build: |
      cd src/maasui
      make
      INSTALL_DIR="$CRAFT_PART_INSTALL/usr/share/maas/web"
      mkdir -p "$INSTALL_DIR"
      cp -a build "$INSTALL_DIR/static"
    prime:
      - usr/share/maas/web/static

  offline-docs:
    plugin: make
    source: src/maas-offline-docs
    make-parameters:
      - BUILD_TYPE=snap

  host-info:
    plugin: make
    source: src/host-info
    build-packages:
      - golang-go

  maas-netmon:
    plugin: make
    source: src/maasagent
    build-packages:
      - golang-go
    organize:
      bin/maas-netmon: usr/sbin/maas-netmon
    prime:
      - usr/sbin/maas-netmon

  maas-agent:
    plugin: make
    source: src/maasagent
    build-packages:
      - golang-go
    organize:
      bin/maas-agent: usr/sbin/maas-agent
    prime:
      - usr/sbin/maas-agent

  tree:
    plugin: dump
    source: snap/local/tree

  snap-preload:
    plugin: make
    source: https://github.com/canonical/snap-preload
    source-type: git

hooks:
  install:
    plugs:
      - mount-observe  # to read /proc/*/mounts
      - network  # to connect to the db for running upgrades
  post-refresh:
    plugs:
      - mount-observe  # to read /proc/*/mounts
      - network  # to connect to the db for running upgrades

layout:
  /etc/libvirt:
    bind: $SNAP/etc/libvirt
  /usr/sbin/ipmi-config:
    bind-file: $SNAP/usr/sbin/ipmi-config
  /etc/freeipmi:
    bind: $SNAP/etc/freeipmi
  /root:
    bind: $SNAP_DATA/root
