#!/usr/bin/env python3
# Copyright 2018 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from provisioningserver.server import run

if __name__ == "__main__":
    run()
