name: CI check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure apt to keep downloaded packages
        run: |
          # Disable the automatic purging of the apt cache in docker images
          sudo rm -f /etc/apt/apt.conf.d/docker-clean
          # Retain downloaded .deb files
          echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' | sudo tee /etc/apt/apt.conf.d/keep-cache

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/required-packages/base'), hashFiles('**/required-packages/dev') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install make and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-dependencies

      - name: Build
        run: make

      - name: Lint
        run: make lint

      - name: Run Tests
        run: make test

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            /work/junit*.xml