name: CI check

on:
  # Run on default events, and also when converted from draft to ready
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.draft }}

    container:
      image: ghcr.io/${{ github.repository }}-build-env:${{ github.event_name == 'merge_group' && 'master' || github.base_ref }}
      volumes:
        - /home/runner/go/pkg/mod:/home/ubuntu/go/pkg/mod
        - /home/runner/.cache/go-build:/home/ubuntu/.cache/go-build
        - ${{ github.workspace }}/maas:/work
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # containers default to sh, make bash as the default
    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          path: ${{ github.workspace }}/maas

      - name: Go modules cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('src/**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go

      - name: Prepare container
        run: |
          pwd
          ls -la .
          git config --global --add safe.directory /work
          make install-dependencies
          make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            /work/junit*.xml
