name: Docs checks
on:
  # Run on default events, and also when converted from draft to ready
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - 'rtd-docs/**'
  merge_group:
    types: [checks_requested]
    paths:
    - 'rtd-docs/**'

jobs:
  lint-and-build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Create venv
      working-directory: "rtd-docs"
      run: make install
    - name: Lint markdown
      working-directory: "rtd-docs"
      run: make lint-md
    - name: Test build
      working-directory: "rtd-docs"
      run: make html
