name: Test coverage and TiCS Report
on:
  workflow_dispatch:
    inputs:
      detach:
        description: "Detach TICS QServer before the run"
        required: false
        default: "false"
  schedule:
    - cron: "30 0 * * 6" # Weekly full analysis
  push:
    branches:
      - "tics-debug-*"

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: read

jobs:
  test-coverage:
    name: Run tests with coverage
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    container:
      image: ghcr.io/${{ github.repository }}-build-env:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - uses: ./.github/actions/ci-setup

      - name: Prepare container
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.coverage"
          chown -R ubuntu:ubuntu "$GITHUB_WORKSPACE/.coverage"

      # - name: Run Python tests with coverage
      #   run: |
      #     COVERAGE_FILE=.coverage.legacy su ubuntu -c "bin/test.region.legacy --with-coverage --cover-branches || true"
      #     COVERAGE_FILE=.coverage.region su ubuntu -c "bin/test.region --with-coverage --cover-branches || true"
      #     COVERAGE_FILE=.coverage.rack su ubuntu -c "bin/test.rack --with-coverage --cover-branches || true"
      #     COVERAGE_FILE=.coverage.pytest su ubuntu -c "bin/pytest --cov=src --cov-branch -n auto --dist=load || true"
      #     su ubuntu -c "python3-coverage combine .coverage.legacy .coverage.region .coverage.rack .coverage.pytest"
      #     su ubuntu -c "python3-coverage report"
      #     su ubuntu -c "python3-coverage xml -o py-coverage.xml"
      #     # The .coverage file is created by python3-coverage. Should be deleted by it, but just to make sure
      #     rm -f ./.coverage
      #     su ubuntu -c "cp py-coverage.xml $GITHUB_WORKSPACE/.coverage/py-coverage.xml"

      - name: Run Go tests with coverage
        run: |
          su ubuntu -c "cd '$GITHUB_WORKSPACE' && make test-go-cover"

          mapfile -t covers < <(find "$GITHUB_WORKSPACE/src" -type f -name cover.out | sort)

          for cover in "${covers[@]}"; do
            mod_dir="$(dirname "$cover")"
            mod_name="$(basename "$mod_dir")"
            out="$GITHUB_WORKSPACE/.coverage/coverage-$mod_name.out"

            mv "$mod_dir/cover.out" "$out"
          done

          ls -lah "$GITHUB_WORKSPACE"
          ls -lah "$GITHUB_WORKSPACE/.coverage"

      - name: Upload coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report
          path: .coverage/*
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 7

  tics-analyzer:
    name: TiCS Analyzer
    needs: test-coverage
    runs-on: [ tiobe ]
    timeout-minutes: 300
    env:
      PROJECT: maas
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 'stable'

      - name: Download coverage
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: coverage-report
          path: .coverage

      - name: Convert Go coverage reports to XML
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang libbpf-dev

          go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.1.0

          cd "$GITHUB_WORKSPACE" && make generate-go || true
          for out in "$GITHUB_WORKSPACE"/.coverage/coverage-*.out; do
            file="$(basename "$out")"
            mod="${file#coverage-}"
            mod="${mod%.out}"

            (
              cd "$GITHUB_WORKSPACE/src/$mod"
              gocov convert "$out" | gocov-xml > "$GITHUB_WORKSPACE/.coverage/coverage-$mod.xml"
            )
          done

      - name: Detach TICS QServer to prevent "project already connected" issue
        if: ${{ github.event.inputs.detach == 'true' }}
        env:
          TICSAUTHTOKEN: ${{ secrets.TICSAUTHTOKEN }}
        run: |
          source ~/.profile
          TICSMaintenance -project ${{ env.PROJECT }} -detach

      - name: Run TiCS Analyzer
        uses: tiobe/tics-github-action@a53037a6bb9f71b6a97cdeb0ac41632266804b9e # v3.8.0
        with:
          mode: qserver
          project: ${{ env.PROJECT }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          tmpdir: /tmp/tics
