#  Copyright 2026 Canonical Ltd.  This software is licensed under the
#  GNU Affero General Public License version 3 (see the file LICENSE).
name: UI Coverage

on:
  schedule:
    - cron: "30 0 * * 6" # Weekly
  push:
    branches:
      - master
      - "tics-debug-*"
    paths:
      - "src/maasui/**"

defaults:
  run:
    working-directory: src/maasui

jobs:
  ui-coverage:
    name: UI Test Coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: src/maasui/.nvmrc
          cache: yarn
          cache-dependency-path: src/maasui/yarn.lock

      - name: Install packages
        run: CYPRESS_INSTALL_BINARY=0 yarn install --frozen-lockfile

      - name: Run tests with coverage
        run: yarn test-coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: src/maasui/coverage
          retention-days: 7
