name: Update API v2 Documentation

on:
  schedule:
    - cron: "0 2 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-build-env:master

permissions:
  contents: write
  packages: read


jobs:
  update-api-docs:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.LANDER_GH_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate and Commit
        run: |
          cd "$GITHUB_WORKSPACE"
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/work \
            -w /work \
            ghcr.io/${{ env.IMAGE_NAME }} \
            sh -c "
              git config --global --add safe.directory /work
              useradd ubuntu || true
              chown -R ubuntu:ubuntu /work
              sudo -H -u ubuntu make install-dependencies
              sudo -H -u ubuntu make build
              sudo -H -u ubuntu bin/maas-region generate_oapi_spec | sudo -H -u ubuntu python3 rtd-docs/_scripts/generate_api_docs.py -
            "
          
          # Restore ownership of git repository
          sudo chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"
          git config user.name "${{ vars.LANDER_USERNAME }}"
          git config user.email "${{ vars.LANDER_EMAIL }}"          
          git add rtd-docs/reference/api-reference/api-v2-generated.md
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "chore(docs): update API v2 documentation"
          git push origin HEAD:master
