name: Launchpad mirror

on:
  schedule:
    - cron: "0 0 * * *" # Everyday at midnight
  workflow_dispatch:

jobs:
  push_to_lp:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Launchpad mirror
        run: |
          KEYFILE="$(mktemp -p "${RUNNER_TEMP:-/tmp}" sshkey-XXXXXX)"
          chmod 600 "$KEYFILE"
          printf '%s' '${{ secrets.LANDER_SSHKEY }}' > "$KEYFILE"
          export GIT_SSH_COMMAND="ssh -i $KEYFILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          git clone --bare "https://github.com/canonical/maas" .
          git push --mirror "git+ssh://maas-lander@git.launchpad.net/maas" --dry-run
          rm -f "$KEYFILE"
