name: Bump MAAS Version

on:
  workflow_dispatch:
    inputs:
      maas_version:
        description: 'MAAS version to bump'
        required: true


permissions:
  contents: write


jobs:
  bump-version:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.LANDER_GH_TOKEN }}

      - name: Bump Version and Push
        run: |
          git config user.name ${{ vars.LANDER_USERNAME }}
          git config user.email ${{ vars.LANDER_EMAIL }}
          ./utilities/version-bump.sh ${{ github.event.inputs.maas_version}}
          git push origin HEAD:${GITHUB_REF_NAME} --tags
