name: maas-power-driver-mscm
version: '1.0.0'
summary: MAAS power driver for IBM MSCM
description: MAAS power driver for IBM MSCM BMCs
grade: devel
confinement: strict
base: core26
build-base: devel

plugs:
  power-driver:
    interface: content
    content: power-driver
    target: $SNAP_COMMON/power-driver

parts:
  mscm-driver:
    plugin: python
    source: .
