#!/usr/bin/env bash
# Copyright 2025 Canonical Ltd.
# This hook is triggered when a driver snap disconnects its power-drivers plug.
# It sends SIGHUP to the maas-agent process to trigger a re-scan.
# maas-agent will detect removed sockets and unregister stale drivers.

set -euo pipefail

if pid=$(pidof maas-agent 2>/dev/null || true); then
    kill -HUP "$pid"
fi
