#!/bin/bash -e
# Copyright 2017 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

mkdir -p \
      "$SNAP_DATA/var/lib/maas" \
      "$SNAP_DATA/root" \
      "$SNAP_DATA/supervisord"
if [ ! -d "$SNAP_COMMON/log" ]; then
    mkdir -m 775 "$SNAP_COMMON/log"
    chown snap_daemon "$SNAP_COMMON/log"
fi

# Always overwrite sample preseeds to ensure samples are up-to-date in case
# we do changes that need to be reflected.
mkdir -p "$SNAP_DATA/preseeds"
cp "$SNAP/etc/maas/preseeds/curtin_userdata" "$SNAP_DATA/preseeds/curtin_userdata.sample"
cp "$SNAP/etc/maas/preseeds/curtin_userdata_centos" "$SNAP_DATA/preseeds/curtin_userdata_centos.sample"
cp "$SNAP/etc/maas/preseeds/curtin_userdata_custom" "$SNAP_DATA/preseeds/curtin_userdata_custom.sample"
cp "$SNAP/etc/maas/preseeds/curtin_userdata_windows" "$SNAP_DATA/preseeds/curtin_userdata_windows.sample"

# Perform migrations. Does nothing in 'rack' or 'none' mode.
"$SNAP/bin/maas-wrapper" migrate --configure
# Force reconfigure of supervisord as config template might have changed
"$SNAP/bin/maas-wrapper" reconfigure-supervisord
