---
title: Deploy Workflow
---
flowchart TD
    A[1 or more ready machines] -->|User selects machines for deployment| B(Input deploy parameters)
    B--> C(DeployMany Workflow execution starts)
    C-->|For each machine| D(Deploy Workflow execution starts)
    D-->E(Fetch power parameters)
    D-->F(Fetch user info)
    E-->G(Resolve DB read activity futures)
    F-->G(Resolve DB read activity futures)
    G-->H{Validate input and permissions}
    H-->|Invalid input and permissions| I[error end]
    H-->J{Set deploy parameters}
    J-->|Conflict| K[error end]
    J-->|Success| L(Power on / cycle machine)
    L-->M{Wait for DHCP Lease}
    M-->|Timeout| L
    M-->|Success| N{Wait for boot assets}
    N-->|Timeout| L
    N-->|Success| O{Wait for curtin start}
    O-->|Timeout| L
    O-->|Success| P{Wait for curtin finish}
    P-->|Timeout| L
    P-->|Success| Q{Is Ephemeral Deployment?}
    Q-->|Yes| W
    Q-->|No| R(Power cycle)
    R-->S{Wait for DHCP Lease}
    S-->|Timeout| R
    S-->|Success| T{Wait for TFTP ACK}
    T-->|Timeout| R
    T-->|Success| U{Wait for cloud-init start}
    U-->|Timeout| R
    U-->|Success| V{Wait for cloud-init finish}
    V-->|Timeout| R
    V-->|Success| W(Update Node Status)
    W--> 'end'
